import type {SendEmail} from '@cloudflare/workers-types';
/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-email-bindings.d.ts --config config/report-email.json --include-runtime false --env-interface LifeAppEmailBindings` (hash: 02f426fced305bf565d4e24b8048d7fd)
interface __BaseEnv_LifeAppEmailBindings {
	REPORT_EMAILS: SendEmail;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_LifeAppEmailBindings {}
}
export interface LifeAppEmailBindings extends __BaseEnv_LifeAppEmailBindings {}
