"use client";
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {WandSparkles,Undo2,Plus,Check} from 'lucide-react';
import AppearancePreview from './appearance-preview';
import {ColorField,colorGroups,colorLabels,relatedColors} from './appearance-fields';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {defaultAppearance,palettes,themeColors,themeVariables,themePresets,applyPreset,activePreset,fontOptions,textScales,defaultTypography,typographyVariables,saveTheme,applyTheme,removeTheme,recommendedColors,recommendationKeys,undoRecommendation,type Appearance,type Typography,type ColorKey,type ThemeColors,type ColorRecommendation} from '@/lib/life/appearance';

type Picker={key:ColorKey;parts:ColorKey[];edits:Partial<ThemeColors>};
export default function AppearanceSettings({value,onChange}:{value?:Appearance;onChange:(value:Appearance)=>void}){
 const [groupIndex,setGroupIndex]=useState(0),[picker,setPicker]=useState<Picker|null>(null),[slotEdit,setSlotEdit]=useState<{slot:number;name:string}|null>(null),[recommendation,setRecommendation]=useState<ColorRecommendation|null>(null),[notice,setNotice]=useState('');
 const expectedValue=useRef(value);
 // A parent Save/Cancel/reload ends transient previews. Our own draft changes keep them.
 useEffect(()=>{if(value!==expectedValue.current){expectedValue.current=value;setNotice('');setRecommendation(null);setPicker(null);setSlotEdit(null);}},[value]);
 function change(next:Appearance){expectedValue.current=next;onChange(next);}
 const appearance=value||defaultAppearance(),colors=themeColors(appearance),safeStyle=themeVariables(palettes[appearance.mode]) as CSSProperties;
 const typography=appearance.typography||defaultTypography(),selectedPreset=activePreset(appearance);
 function changeTypography(next:Typography){change({...appearance,typography:next});}
 const canUndo=recommendation&&recommendationKeys(recommendation).some(key=>({...palettes[recommendation.mode],...appearance.custom[recommendation.mode]})[key].toLowerCase()===recommendation.after[key].toLowerCase());
 function color(key:ColorKey,next:string){change({...appearance,custom:{...appearance.custom,[appearance.mode]:{...appearance.custom[appearance.mode],[key]:next}}});}
 function choose(next:Appearance){setRecommendation(null);setNotice('');change(next);}
 function recommend(){
  const next={mode:appearance.mode,before:{...appearance.custom[appearance.mode]},after:recommendedColors(colors,appearance.mode)};
  if(!recommendationKeys(next).length){setNotice('Your colors already suit the recommended text and control contrast.');return;}
  setRecommendation(next);setNotice('Recommended colors are previewing. Undo to return to your colors.');
  const changes=Object.fromEntries(recommendationKeys(next).map(key=>[key,next.after[key]]));
  change({...appearance,custom:{...appearance.custom,[appearance.mode]:{...appearance.custom[appearance.mode],...changes}}});
 }
 function openPicker(key:ColorKey){setPicker({key,parts:relatedColors(key),edits:{}});}
 return <details className="settings-group appearance-settings"><summary><strong>Appearance</strong><span>Color themes, fonts & text size</span></summary><div className="appearance-safe" style={safeStyle}>
 <div className="appearance-presets"><h3>Choose a palette</h3><p>Start with a favorite, then make the colors your own.</p><div className="preset-options" role="group" aria-label="Color presets">{themePresets.map(preset=><button type="button" key={preset.id} className="preset-option" aria-label={'Use '+preset.name+' palette'} aria-pressed={selectedPreset?.id===preset.id} onClick={()=>choose(applyPreset(appearance,preset.id))}>
 <span className="preset-preview" aria-hidden="true" style={themeVariables(preset.colors) as CSSProperties}><span className="preset-swatch"><i/><i/><i/></span><span className="preset-mini-card"><i/><i/><i/></span></span><span className="preset-name">{preset.name}{selectedPreset?.id===preset.id&&<Check aria-hidden="true"/>}</span><span className="preset-description">{preset.description}</span></button>)}</div></div>
 <div className="theme-options" role="group" aria-label="Color mode">{(['oled','light'] as const).map(mode=>{const modeColors=themeColors({...appearance,mode});return <button type="button" key={mode} aria-pressed={appearance.mode===mode} onClick={()=>choose({...appearance,mode})}><span className="theme-swatch" aria-hidden="true" style={{background:modeColors.background,borderColor:modeColors.input}}><i style={{background:modeColors.primary}}/><i style={{background:modeColors.secondary}}/></span><strong>{mode==='oled'?'Dark colors':'Light colors'}</strong><small>Return to your {mode==='oled'?'dark':'light'} palette</small></button>;})}</div>
 <section className="appearance-typography" aria-labelledby="appearance-typography-title"><h3 id="appearance-typography-title">Font & size</h3><div className="typography-controls"><label>Interface font<select aria-label="Interface font" value={typography.font} onChange={e=>changeTypography({...typography,font:e.target.value as Typography['font']})}>{fontOptions.map(font=><option key={font.id} value={font.id}>{font.label}</option>)}</select></label><label>Text size<select aria-label="Text size" value={typography.scale} onChange={e=>changeTypography({...typography,scale:Number(e.target.value) as Typography['scale']})}>{textScales.map(scale=><option key={scale} value={scale}>{scale}%{scale===100?' (default)':''}</option>)}</select></label></div><div className="typography-sample" style={{...themeVariables(colors),...typographyVariables(typography)} as CSSProperties}><strong>A little progress, every day.</strong><p>Your journal, movement, and money, in a style that feels like you.</p><small>Aa Bb Cc · 0123456789 · $1,234.56</small></div><Button variant="ghost" onClick={()=>changeTypography(defaultTypography())}>Reset font & size</Button></section>
 <div className="custom-theme-heading"><h3>Your themes</h3><small>3 custom slots</small></div><div className="saved-themes">{[1,2,3].map(slot=>{const theme=appearance.savedThemes?.find(t=>t.slot===slot);return <div key={slot} className="saved-theme">{theme?<><button type="button" className="saved-theme-apply" aria-label={'Apply '+theme.name} onClick={()=>choose(applyTheme(appearance,slot))}><span className="saved-theme-colors" aria-hidden="true">{(['background','primary','accent','chart5','muscleHigh'] as const).map(key=><i key={key} style={{background:theme.colors[key]}}/>)}</span><strong>{theme.name}</strong><small>{theme.mode==='oled'?'Dark':'Light'}{theme.typography?' · '+fontOptions.find(font=>font.id===theme.typography?.font)?.label+' · '+theme.typography.scale+'%':''} · Apply theme</small></button><div className="saved-theme-actions"><button type="button" aria-label={'Update '+theme.name} onClick={()=>setSlotEdit({slot,name:theme.name})}>Update</button><button type="button" aria-label={'Remove '+theme.name} onClick={()=>{change(removeTheme(appearance,slot));setNotice('Theme removed from your draft. Cancel changes restores saved themes.');}}>Remove</button></div></>:<button type="button" className="saved-theme-empty" onClick={()=>setSlotEdit({slot,name:'My theme '+slot})}><Plus/><span>Save theme {slot}</span></button>}</div>;})}</div>
 <p className="muted">Colors, fonts, text size, and custom themes preview immediately. Save Settings to keep them on your account, or Cancel changes to restore your saved settings.</p>
 <details className="palette-editor"><summary>Customize colors</summary><div className="palette-recommendation"><Button variant="outline" onClick={recommend} disabled={!!canUndo}><WandSparkles/>Preview recommended colors</Button>{canUndo&&<Button variant="ghost" onClick={()=>{change(undoRecommendation(appearance,recommendation!));setRecommendation(null);setNotice('Recommended changes undone.');}}><Undo2/>Undo recommendation</Button>}{canUndo&&<Button variant="ghost" onClick={()=>{setRecommendation(null);setNotice('Colors kept in your draft. Save Settings when ready.');}}>Keep colors</Button>}<small>Optional adjustments for easier-to-read text and controls.</small></div>{notice&&<p className="palette-notice" role="status">{notice}</p>}
 <div className="palette-layout"><div className="palette-preview-column"><h3>Click to customize</h3><p>Choose an element or muscle on the preview to open its color picker.</p><AppearancePreview colors={{...colors,...picker?.edits}} onPick={openPicker}/></div><div className="palette-controls"><div className="palette-groups" role="group" aria-label="Color groups">{colorGroups.map((group,index)=><button type="button" key={group.title} aria-pressed={groupIndex===index} onClick={()=>setGroupIndex(index)}>{group.title}</button>)}</div>{colorGroups.filter((_,index)=>index===groupIndex).map(group=><fieldset key={group.title}><legend>{group.title}</legend><div className="color-grid">{group.fields.map(([key,label])=><ColorField key={appearance.mode+':'+key} label={label} value={colors[key]} onChange={v=>color(key,v)}/>)}</div></fieldset>)}</div></div></details>
 <Button className="reset-theme" variant="ghost" onClick={()=>choose({...appearance,custom:{...appearance.custom,[appearance.mode]:{}}})}>Reset {appearance.mode==='oled'?'OLED':'light'} colors</Button>
 </div>
 <Dialog open={!!picker} onOpenChange={open=>{if(!open)setPicker(null);}}><DialogContent className="appearance-color-dialog" style={safeStyle}><DialogHeader><DialogTitle>Edit {picker?colorLabels[picker.key]:'color'}</DialogTitle><DialogDescription>Choose a color, then Apply. Cancel leaves your palette unchanged.</DialogDescription></DialogHeader>{picker&&<>{picker.parts.length>1&&<label className="color-part">Element part<select aria-label="Element part" value={picker.key} onChange={e=>setPicker({...picker,key:e.target.value as ColorKey})}>{picker.parts.map(key=><option key={key} value={key}>{colorLabels[key]}</option>)}</select></label>}<ColorField key={picker.key} label={colorLabels[picker.key]} value={picker.edits[picker.key]||colors[picker.key]} onChange={next=>setPicker({...picker,edits:{...picker.edits,[picker.key]:next}})}/><div className="color-dialog-swatch" style={{background:picker.edits[picker.key]||colors[picker.key]}} aria-label="Selected color"/><DialogFooter><Button variant="ghost" onClick={()=>setPicker(null)}>Cancel</Button><Button onClick={()=>{change({...appearance,custom:{...appearance.custom,[appearance.mode]:{...appearance.custom[appearance.mode],...picker.edits}}});setPicker(null);}}>Apply color</Button></DialogFooter></>}</DialogContent></Dialog>
 <Dialog open={!!slotEdit} onOpenChange={open=>{if(!open)setSlotEdit(null);}}><DialogContent className="appearance-color-dialog" style={safeStyle}><DialogHeader><DialogTitle>{slotEdit&&appearance.savedThemes?.some(t=>t.slot===slotEdit.slot)?'Update custom theme':'Save custom theme'}</DialogTitle><DialogDescription>Store the current colors, font, and text size in slot {slotEdit?.slot}. Save Settings afterwards to keep this theme on your account.</DialogDescription></DialogHeader>{slotEdit&&<><label className="color-part">Theme name<input aria-label="Theme name" maxLength={40} value={slotEdit.name} onChange={e=>setSlotEdit({...slotEdit,name:e.target.value})}/></label><DialogFooter><Button variant="ghost" onClick={()=>setSlotEdit(null)}>Cancel</Button><Button disabled={!slotEdit.name.trim()} onClick={()=>{change(saveTheme(appearance,slotEdit.slot,slotEdit.name));setNotice('Theme saved in your draft. Save Settings to keep it.');setSlotEdit(null);}}>Save theme</Button></DialogFooter></>}</DialogContent></Dialog>
 </details>;
}
