"use client";
import {useState,type CSSProperties,type ReactNode,type MouseEvent} from 'react';
import {Check,Info,TriangleAlert} from 'lucide-react';
import {themeVariables,type ThemeColors,type ColorKey} from '@/lib/life/appearance';
import {muscleIds,muscleNames,type MuscleId} from '@/lib/life/muscle-groups';
import type {MuscleVolume} from '@/lib/life/muscle-volume';
import {colorLabels} from './appearance-fields';
import MuscleMap from './muscle-map';

const examples=Object.fromEntries(muscleIds.map((id,index)=>[id,{direct:[0,3,7,12][index%4],indirect:0,estimated:[0,3,7,12][index%4]}])) as Record<MuscleId,MuscleVolume>;
export default function AppearancePreview({colors,onPick}:{colors:ThemeColors;onPick:(key:ColorKey)=>void}){
 const [selected,setSelected]=useState<MuscleId|null>(null);
 function pick(key:ColorKey,children:ReactNode,className='preview-pick',style?:CSSProperties){return <button type="button" className={className} style={style} aria-label={'Edit '+colorLabels[key]+' color'} title={'Edit '+colorLabels[key]} onClick={e=>{e.stopPropagation();onPick(key);}}>{children}</button>;}
 const surface=(key:ColorKey)=>({onClick:(e:MouseEvent)=>{if(e.target===e.currentTarget)onPick(key);},title:'Edit '+colorLabels[key]});
 return <section className="palette-preview" aria-label="Live color preview" style={themeVariables(colors) as CSSProperties} {...surface('background')}>
  <div className="preview-nav" {...surface('nav')}>{pick('nav',<strong>LifeApp</strong>)}{pick('background','Page background','preview-pick preview-surface-label')}</div>
  <div className="preview-card" {...surface('card')}><div className="preview-heading">{pick('foreground',<strong>A little perspective</strong>)}{pick('card','Card','preview-pick preview-surface-label')}</div><p>{pick('mutedForeground','See your text, surfaces and everyday controls.')}</p><div className="preview-buttons">{pick('primary','Primary','theme-example-primary')}{pick('secondary','Secondary','theme-example-secondary')}{pick('accent','Selected','theme-example-selected')}{pick('destructive','Delete','theme-example-delete')}</div>{pick('inputBackground','Your journal goes here','preview-input')}<div className="preview-popover" {...surface('popover')}>{pick('popover','Menu or dialog')}<small>{pick('mutedForeground','Secondary text')}</small></div><div className="preview-status">{pick('success',<><Check/>Saved</>,'preview-pick',{color:'var(--success)'})}{pick('warning',<><TriangleAlert/>Upcoming</>,'preview-pick',{color:'var(--warning)'})}{pick('info',<><Info/>Information</>,'preview-pick',{color:'var(--info)'})}</div></div>
  <div className="preview-card" {...surface('card')}><div className="preview-habit-heading"><strong>Read a few pages</strong>{pick('chart5','75%','preview-pick preview-habit-score')}</div><div className="response-choices" role="group" aria-label="Example habit choices">{pick('accent','Done','response-choice selected')}{pick('secondary','Missed','response-choice')}{pick('secondary','Exempt','response-choice')}</div><div className="allowance-row preview-allowance"><strong>Groceries <span>$120 left</span></strong>{pick('chart3',<progress aria-label="Example category allowance" value={280} max={400}/>,'preview-pick preview-progress')}<small>$280 / $400 · $35 upcoming</small></div><div className="preview-trends"><svg viewBox="0 0 200 50" role="img" aria-label="Example budget and movement trends"><polyline className="preview-trend-line" onClick={()=>onPick('chart1')} points="0,35 40,25 80,30 120,18 160,22 200,8" fill="none" stroke="var(--chart-1)" strokeWidth="3"/><polyline className="preview-trend-line" onClick={()=>onPick('chart2')} points="0,45 40,39 80,20 120,30 160,16 200,20" fill="none" stroke="var(--chart-2)" strokeWidth="3"/></svg><div>{pick('chart1','Budget','preview-pick',{color:'var(--chart-1)'})}{pick('chart2','Movement','preview-pick',{color:'var(--chart-2)'})}</div><small>Rest timer {pick('chart4',<strong>1:30</strong>,'preview-pick',{color:'var(--chart-4)'})}</small></div></div>
  <div className="preview-card preview-muscles" {...surface('card')}><div><strong>Muscle coverage</strong><small>{selected?`${muscleNames[selected]} · ${examples[selected].estimated} example sets`:'Click a muscle to edit its color range.'}</small></div><MuscleMap volumes={examples} selected={selected} onSelect={id=>{setSelected(id);const sets=examples[id].estimated;onPick(sets===0?'muscleEmpty':sets<5?'muscleLow':sets<10?'muscleMid':'muscleHigh');}}/><div className="preview-muscle-legend">{(['muscleEmpty','muscleLow','muscleMid','muscleHigh'] as const).map((key,index)=><span key={key}>{pick(key,<><i style={{background:colors[key]}}/>{['0','1–4','5–9','10+'][index]}</>)}</span>)}</div></div>
  {pick('border','Dividers','preview-pick preview-divider')}
 </section>;
}
