"use client";
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {todayIn,type Profile} from '@/lib/life/domain';
import {budgetSchema,transactionSchema,budgetSummary,dueDate,money,parseMoney,type Budget,type Transaction,type Saved} from '@/lib/life/modules';
import {Choice,request,saveRecord,useUnsaved} from './shared';
const kinds=[{value:'expense',label:'Expense'},{value:'income',label:'Income'},{value:'saving',label:'Move to savings'},{value:'investing',label:'Move to investments'}];
const weekdays=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const goals=['spending','saving','investing'] as const;
const blankPlan=():Budget=>budgetSchema.parse({currency:'USD',categories:['Housing','Groceries','Dining out','Transport','Bills','Personal'].map(name=>({id:crypto.randomUUID(),name,limitCents:0})),recurring:[],goals:{spending:'',saving:'',investing:''}});
const blankTransaction=(date:string):Saved<Transaction>=>({id:crypto.randomUUID(),version:0,data:{date,kind:'expense',amountCents:0,categoryId:'',categoryName:'',note:'',recurringId:null,voided:false}});
function Amount({label,cents,onChange}:{label:string;cents:number;onChange:(v:number)=>void}){
 const [text,setText]=useState(cents>0?(cents/100).toFixed(2):'');useEffect(()=>{try{if(cents>=0&&parseMoney(text||'0')!==cents)setText(cents?(cents/100).toFixed(2):'');}catch{}},[cents]);
 return <label className="compact-field">{label}<input inputMode="decimal" placeholder="0.00" value={text} onChange={e=>{setText(e.target.value);try{onChange(e.target.value===''?0:parseMoney(e.target.value));}catch{onChange(-1);}}}/>{cents<0&&<small>Enter dollars and cents.</small>}</label>;
}
export default function BudgetPanel({profile,onDirty,onSettings,onProfileSaved}:{profile:Profile;onDirty:(v:boolean)=>void;onSettings:()=>void;onProfileSaved:(p:Profile)=>void}){
 const today=todayIn(profile.timezone),[month,setMonth]=useState(today.slice(0,7)),[plan,setPlan]=useState<Saved<Budget>|null>(null),[transactions,setTransactions]=useState<Saved<Transaction>[]>([]);
 const [draft,setDraft]=useState<Saved<Transaction>|null>(null),[location,setLocation]=useState('new'),[amount,setAmount]=useState(''),[planDirty,setPlanDirty]=useState(false),[txDirty,setTxDirty]=useState(false),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [pending,setPending]=useState<{kind:'budget';record:Saved<Budget>}|{kind:'transaction';record:Saved<Transaction>}|null>(null);
 useUnsaved(planDirty||txDirty||!!pending||(busy&&ready),onDirty);
 function clearDraft(){setDraft(blankTransaction(month===today.slice(0,7)?today:month+'-01'));setLocation('new');setAmount('');setTxDirty(false);}
 async function load(){setBusy(true);setReady(false);setError('');try{
  const [plans,tx]=await Promise.all([request('?kind=budget'),request('?kind=transaction&month='+month)]);
  const existing=plans.records.find((p:Saved<Budget>)=>p.id===month),earlier=plans.records.filter((p:Saved<Budget>)=>p.id<month).sort((a:Saved<Budget>,b:Saved<Budget>)=>b.id.localeCompare(a.id))[0];
  setPlan(existing?{...existing,data:budgetSchema.parse(existing.data)}:{id:month,version:0,data:earlier?budgetSchema.parse(earlier.data):blankPlan()});setTransactions(tx.records);clearDraft();setPlanDirty(false);setPending(null);setReady(true);setNotice('');
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{void load();},[month]);
 function editPlan(data:Budget){if(plan)setPlan({...plan,data});setPlanDirty(true);setNotice('');}
 function editRecurring(id:string,patch:Partial<Budget['recurring'][number]>){if(plan)editPlan({...plan.data,recurring:plan.data.recurring.map(r=>r.id===id?{...r,...patch}:r)});}
 function editTx(patch:Partial<Transaction>){if(draft)setDraft({...draft,data:{...draft.data,...patch}});setTxDirty(true);setNotice('');}
 async function persist(item:NonNullable<typeof pending>){setPending(item);setBusy(true);setError('');try{
  if(item.kind==='budget'){
   const saved=await saveRecord('budget',item.record);setPlan(saved);setPlanDirty(false);setPending(null);setNotice('Plan saved.');
   if(!profile.budgetGoals&&goals.some(k=>saved.data.goals[k].trim())){try{const result=await request('',{action:'profile',profile:{...profile,budgetGoals:saved.data.goals}});onProfileSaved(result.profile);}catch{setError('Your plan and goals are saved. Open Settings to finish moving your goals there.');}}
  }else{const saved=await saveRecord('transaction',item.record);setTransactions(prev=>[saved,...prev.filter(t=>t.id!==saved.id)]);clearDraft();setPending(null);setNotice('Transaction saved.');}
 }catch(e){setError((e as Error).message);if((e as {status?:number}).status&&((e as {status:number}).status<500))setPending(null);}finally{setBusy(false);}}
 function savePlan(){if(!plan)return;const result=budgetSchema.safeParse(plan.data);if(!result.success){setError('Check category names, amounts and recurring estimates. Every recurring item requires an amount greater than zero.');return;}void persist({kind:'budget',record:{...plan,data:result.data}});}
 function saveTx(){if(!draft)return;try{if(!draft.data.date.startsWith(month+'-'))throw Error('Choose a date in the selected month.');const data=transactionSchema.parse({...draft.data,amountCents:parseMoney(amount)});void persist({kind:'transaction',record:{...draft,data}});}catch{setError('Enter an actual amount greater than zero and a valid date in this month.');}}
 function openTx(record:Saved<Transaction>,where:string,variable=false){if(txDirty){setError('Save or cancel your current transaction first.');return;}setDraft(structuredClone(record));setLocation(where);setAmount(variable?'':(record.data.amountCents/100).toFixed(2));setTxDirty(true);setError('');}
 const summary=plan?budgetSummary(plan.data,transactions,month):null;
 const transactionForm=plan&&draft&&<div className="inline-transaction"><div className="form-grid">
  <label className="compact-field">Type<Choice label="Transaction type" value={draft.data.kind} options={draft.data.recurringId?kinds.filter(k=>k.value===draft.data.kind):kinds} onChange={kind=>editTx({kind:kind as Transaction['kind'],categoryId:''})}/></label>
  <label className="compact-field">{draft.data.recurringId?'Actual amount (USD)':'Amount (USD)'}<input aria-label="Transaction amount" inputMode="decimal" placeholder={draft.data.recurringId?'Estimate '+money(draft.data.amountCents):'0.00'} value={amount} onChange={e=>{setAmount(e.target.value);setTxDirty(true);}}/></label>
  <label className="compact-field">Date<input type="date" min={month+'-01'} max={month===today.slice(0,7)?today:dueDate(month,31)} value={draft.data.date} onChange={e=>editTx({date:e.target.value})}/></label>
  {draft.data.kind==='expense'&&<label className="compact-field">Category<Choice label="Expense category" value={draft.data.categoryId} options={plan.data.categories.filter(c=>(!c.archived||c.id===draft.data.categoryId)&&(!draft.data.recurringId||c.id===draft.data.categoryId)).map(c=>({value:c.id,label:c.name}))} onChange={categoryId=>editTx({categoryId})}/></label>}
 </div><label className="compact-field">Description<input maxLength={300} value={draft.data.note} placeholder="e.g. Lunch" onChange={e=>editTx({note:e.target.value})}/></label>
 {draft.version>0&&<label className="inline-check"><input type="checkbox" checked={draft.data.voided} onChange={e=>editTx({voided:e.target.checked})}/>Void transaction</label>}
 <div className="action-row"><Button disabled={!amount||!plan.version||planDirty||!!pending} onClick={saveTx}>Save transaction</Button><Button variant="ghost" onClick={clearDraft}>Cancel</Button></div>{(!plan.version||planDirty)&&<small>Save the monthly plan first.</small>}</div>;
 function transactionRow(t:Saved<Transaction>,prefix='history'){return <div className="transaction-tile" key={t.id}>{location===prefix+':'+t.id?transactionForm:<div className="ledger-row"><span><strong>{t.data.note||kinds.find(k=>k.value===t.data.kind)?.label}{t.data.voided?' · Voided':''}</strong><small>{t.data.date} · {t.data.categoryName||t.data.kind}</small></span><strong>{money(t.data.amountCents)}</strong><Button variant="ghost" disabled={txDirty} onClick={()=>openTx(t,prefix+':'+t.id)}>Edit</Button></div>}</div>;}
 return <section className="budget-workspace"><div className="budget-toolbar"><h2>Your month</h2><label className="compact-field">Month<input aria-label="Budget month" type="month" value={month} disabled={busy||planDirty||txDirty||!!pending} onChange={e=>{if(e.target.value)setMonth(e.target.value);}}/></label></div>
 {error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}
 {pending&&!busy&&<p className="notice">Save unconfirmed. <Button onClick={()=>persist(pending)}>Retry exact save</Button></p>}
 {!ready?<Button disabled={busy} onClick={load}>{busy?'Opening budget…':'Retry budget'}</Button>:plan&&summary&&<fieldset disabled={busy||!!pending}>
 <div className="metric-grid budget-metrics">{[['Income',summary.income],['Spent',summary.expenses],['Saved / invested',summary.saving+summary.investing],['Cash flow',summary.cashFlow]].map(([label,value])=><div key={label}><small>{label}</small><strong>{money(value as number)}</strong></div>)}</div>
 <div className="budget-columns"><section className="module-card quick-transaction"><h3>Quick transaction</h3>{location==='new'?transactionForm:<p className="muted">Editing in the selected transaction below.</p>}</section>
 <section className="module-card category-allowances"><div className="section-heading"><h3>Category allowances</h3>{(!plan.version||planDirty)&&<Button onClick={savePlan}>Save plan</Button>}</div>
 {summary.categories.filter(c=>!c.archived).map(c=><details className="allowance-row" key={c.id}><summary><span>{c.name}</span><strong className={c.remaining<0?'negative':''}>{money(c.remaining)} left</strong><progress aria-label={`${c.name} allowance used`} value={Math.min(c.spent,c.limitCents)} max={c.limitCents||1}/><small>{money(c.spent)} / {money(c.limitCents)}{c.scheduled>0?` · ${money(c.scheduled)} upcoming`:''}{summary.due.some(r=>r.categoryId===c.id&&r.variable&&!r.recorded&&r.date<=today)?' · Needs actual amount':''}</small></summary>
 <div className="allowance-content"><div className="form-grid"><label className="compact-field">Category name<input value={c.name} maxLength={100} onChange={e=>editPlan({...plan.data,categories:plan.data.categories.map(x=>x.id===c.id?{...x,name:e.target.value}:x)})}/></label><Amount label="Monthly allowance (USD)" cents={c.limitCents} onChange={limitCents=>editPlan({...plan.data,categories:plan.data.categories.map(x=>x.id===c.id?{...x,limitCents}:x)})}/></div>
 <p className="muted">{money(c.afterScheduled)} left after expected payments.</p>{transactions.filter(t=>!t.data.voided&&t.data.kind==='expense'&&t.data.categoryId===c.id).map(t=>transactionRow(t,c.id))}
 {!transactions.some(t=>!t.data.voided&&t.data.kind==='expense'&&t.data.categoryId===c.id)&&<p className="muted">No recorded expenses in this category.</p>}
 <Button variant="ghost" onClick={()=>editPlan({...plan.data,categories:plan.data.categories.map(x=>x.id===c.id?{...x,archived:true}:x)})}>Archive category</Button></div></details>)}
 <div className="action-row"><Button variant="ghost" disabled={plan.data.categories.length>=30} onClick={()=>editPlan({...plan.data,categories:[...plan.data.categories,{id:crypto.randomUUID(),name:'New category',limitCents:0,archived:false}]})}>+ Category</Button>{planDirty&&<Button variant="ghost" disabled={txDirty} onClick={load}>Cancel plan changes</Button>}</div>
 {!!plan.data.categories.filter(c=>c.archived).length&&<details><summary>Archived categories</summary>{plan.data.categories.filter(c=>c.archived).map(c=><Button key={c.id} variant="ghost" onClick={()=>editPlan({...plan.data,categories:plan.data.categories.map(x=>x.id===c.id?{...x,archived:false}:x)})}>Restore {c.name}</Button>)}</details>}
 <details className="recurring-settings"><summary>Recurring income & expenses <span>{plan.data.recurring.filter(r=>r.active).length}</span></summary>
 {plan.data.recurring.map(r=><details className="recurring-item" key={r.id}><summary>{r.title}{r.variable?' · Variable':''}{!r.active?' · Paused':''}</summary><div className="form-grid">
 <label className="compact-field">Name<input maxLength={100} value={r.title} onChange={e=>editRecurring(r.id,{title:e.target.value})}/></label><label className="compact-field">Type<Choice label="Recurring type" value={r.kind} options={kinds.slice(0,2)} onChange={v=>editRecurring(r.id,{kind:v as 'expense'|'income',categoryId:v==='income'?'':plan.data.categories.find(c=>!c.archived)?.id||''})}/></label>
 <label className="inline-check"><input type="checkbox" checked={r.variable} onChange={e=>editRecurring(r.id,{variable:e.target.checked})}/>Variable amount</label><Amount label={r.variable?'Required estimate (USD)':'Amount (USD)'} cents={r.amountCents} onChange={amountCents=>editRecurring(r.id,{amountCents})}/>
 <label className="compact-field">Repeat by<Choice label="Recurring frequency" value={r.frequency} options={[{value:'monthly-day',label:'Day of month'},{value:'monthly-weekday',label:'Weekday of month'}]} onChange={frequency=>editRecurring(r.id,{frequency:frequency as typeof r.frequency})}/></label>
 {r.frequency==='monthly-day'?<label className="compact-field">Day<input type="number" min={1} max={31} value={r.day} onChange={e=>editRecurring(r.id,{day:Number(e.target.value)})}/></label>:<><label className="compact-field">Which week<Choice label="Recurring week" value={r.week} options={['first','second','third','fourth','last'].map(value=>({value,label:value[0].toUpperCase()+value.slice(1)}))} onChange={week=>editRecurring(r.id,{week:week as typeof r.week})}/></label><label className="compact-field">Weekday<Choice label="Recurring weekday" value={String(r.weekday)} options={weekdays.map((label,i)=>({value:String(i),label}))} onChange={weekday=>editRecurring(r.id,{weekday:Number(weekday)})}/></label></>}
 {r.kind==='expense'&&<label className="compact-field">Category<Choice label="Recurring category" value={r.categoryId} options={plan.data.categories.map(c=>({value:c.id,label:c.name}))} onChange={categoryId=>editRecurring(r.id,{categoryId})}/></label>}
 <label className="inline-check"><input type="checkbox" checked={r.active} onChange={e=>editRecurring(r.id,{active:e.target.checked})}/>Active this month</label></div></details>)}
 <Button variant="outline" disabled={plan.data.recurring.length>=60} onClick={()=>editPlan({...plan.data,recurring:[...plan.data.recurring,{id:crypto.randomUUID(),title:'New recurring item',kind:'expense',categoryId:plan.data.categories[0]?.id||'',amountCents:0,day:1,frequency:'monthly-day',week:'first',weekday:1,variable:false,active:true}]})}>Add recurring item</Button><small>Estimates reserve room in your budget. Confirm payments when they happen.</small></details>
 {!plan.version&&!profile.budgetGoals&&<details className="budget-initial-goals"><summary>What are you working toward?</summary>{goals.map(key=><label className="compact-field" key={key}>{key[0].toUpperCase()+key.slice(1)} goal<textarea rows={2} maxLength={1000} value={plan.data.goals[key]} onChange={e=>editPlan({...plan.data,goals:{...plan.data.goals,[key]:e.target.value}})}/></label>)}<small>You can adjust these later in Settings.</small></details>}
 {(!plan.version||planDirty)&&<Button onClick={savePlan}>Save monthly plan</Button>}</section></div>
 <div className="budget-columns budget-history"><section className="module-card"><h3>Transaction history</h3>{!transactions.length&&<p className="muted">Your recorded transactions appear here.</p>}{[...transactions].sort((a,b)=>b.data.date.localeCompare(a.data.date)).map(t=>transactionRow(t))}</section>
 <section className="module-card"><h3>Expected income & expenses</h3><div className="forecast-totals"><span>Income <strong>{money(summary.due.filter(r=>!r.recorded&&r.kind==='income').reduce((n,r)=>n+r.amountCents,0))}</strong></span><span>Expenses <strong>{money(summary.due.filter(r=>!r.recorded&&r.kind==='expense').reduce((n,r)=>n+r.amountCents,0))}</strong></span></div>
 {!summary.due.length&&<p className="muted">Add recurring items inside Category allowances.</p>}{[...summary.due].sort((a,b)=>a.date.localeCompare(b.date)).map(r=><div className={`transaction-tile ${!r.recorded&&r.variable&&r.date<=today?'needs-amount':''}`} key={r.id}>{location==='due:'+r.id?transactionForm:<div className="ledger-row"><span><strong>{r.title}</strong><small>{r.date} · {r.kind}{r.recorded?' · Recorded':r.variable&&r.date<=today?' · Needs actual amount':r.variable?' · Variable estimate':' · Expected'}</small></span><strong>{money(r.recorded?r.actualCents:r.amountCents)}{r.variable&&!r.recorded&&<small>Estimated</small>}</strong><Button variant="ghost" disabled={r.recorded||!plan.version||planDirty||txDirty||r.date>today} onClick={()=>{const existing=transactions.find(t=>t.id===r.id);openTx(existing?{...existing,data:{...existing.data,voided:false}}:{id:r.id,version:0,data:{date:r.date,kind:r.kind,amountCents:r.amountCents,categoryId:r.categoryId,categoryName:'',note:r.title,recurringId:plan.data.recurring.find(x=>'due:'+month+':'+x.id===r.id)!.id,voided:false}},'due:'+r.id,r.variable);}}>{r.variable?'Enter actual':'Confirm'}</Button></div>}</div>)}</section></div>
 <footer className="budget-footer"><span>Recorded totals exclude estimates.</span><button onClick={onSettings}>Budget goals in Settings ↗</button></footer>
 </fieldset>}</section>;
}
