"use client";
import { useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import { todayIn, type Profile } from '@/lib/life/domain';
import { budgetSummary, dueDate, money, parseMoney, type Budget, type Transaction, type Saved } from '@/lib/life/modules';
import { Choice, request, saveRecord, useUnsaved } from './shared';
const kinds=[{value:'expense',label:'Expense'},{value:'income',label:'Income'},{value:'saving',label:'Move to savings'},{value:'investing',label:'Move to investments'}];
const blankPlan=():Budget=>({currency:'USD',categories:['Housing','Groceries','Dining out','Transport','Bills','Personal'].map(name=>({id:crypto.randomUUID(),name,limitCents:0})),recurring:[],goals:{spending:'',saving:'',investing:''}});
const blankTransaction=(date:string):Saved<Transaction>=>({id:crypto.randomUUID(),version:0,data:{date,kind:'expense',amountCents:0,categoryId:'',categoryName:'',note:'',recurringId:null,voided:false}});
function Amount({label,cents,onChange}:{label:string;cents:number;onChange:(v:number)=>void}){const [text,setText]=useState((cents/100).toFixed(2));const [error,setError]=useState('');useEffect(()=>setText((cents/100).toFixed(2)),[cents]);return <label className="compact-field">{label}<input inputMode="decimal" value={text} onChange={e=>{setText(e.target.value);try{onChange(parseMoney(e.target.value));setError('');}catch{setError('Use dollars and cents.');}}} onBlur={()=>{if(error){setText((cents/100).toFixed(2));setError('');}}}/>{error&&<small>{error} Last valid amount retained.</small>}</label>;}
export default function BudgetPanel({profile,onDirty}:{profile:Profile;onDirty:(v:boolean)=>void}){
 const today=todayIn(profile.timezone),[month,setMonth]=useState(today.slice(0,7)),[plan,setPlan]=useState<Saved<Budget>|null>(null),[transactions,setTransactions]=useState<Saved<Transaction>[]>([]),[transaction,setTransaction]=useState<Saved<Transaction>|null>(null),[amount,setAmount]=useState(''),[planDirty,setPlanDirty]=useState(false),[transactionDirty,setTransactionDirty]=useState(false),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useUnsaved(planDirty||transactionDirty||busy,onDirty);
 async function load(){setBusy(true);setReady(false);setError('');try{const [plans,tx]=await Promise.all([request('?kind=budget'),request('?kind=transaction&month='+month)]);const existing=plans.records.find((p:Saved<Budget>)=>p.id===month);const earlier=plans.records.filter((p:Saved<Budget>)=>p.id<month).sort((a:Saved<Budget>,b:Saved<Budget>)=>b.id.localeCompare(a.id))[0];setPlan(existing||{id:month,version:0,data:earlier?structuredClone(earlier.data):blankPlan()});setTransactions(tx.records);setTransaction(blankTransaction(month===today.slice(0,7)?today:month+'-01'));setAmount('');setPlanDirty(false);setTransactionDirty(false);setReady(true);setNotice(existing?'':earlier?'Your previous monthly plan is carried forward. Review and save it for this month.':'Set your category allowances, then save this month’s plan.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{load();},[month]);
 function editPlan(next:Budget){if(plan)setPlan({...plan,data:next});setPlanDirty(true);setNotice('');}
 function editTransaction(next:Transaction){if(transaction)setTransaction({...transaction,data:next});setTransactionDirty(true);setNotice('');}
 async function savePlan(){if(!plan)return;setBusy(true);setError('');try{const saved=await saveRecord('budget',plan);setPlan(saved);setPlanDirty(false);setNotice('Monthly plan saved. Scheduled items remain forecasts until you log them.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function saveTransaction(){if(!transaction)return;if(!transaction.data.date.startsWith(month+'-')){setError('Choose a date in the selected month.');return;}setBusy(true);setError('');try{const saved=await saveRecord('transaction',{...transaction,data:{...transaction.data,amountCents:parseMoney(amount)}});setTransactions(prev=>[saved,...prev.filter(t=>t.id!==saved.id)]);setTransaction(blankTransaction(month===today.slice(0,7)?today:month+'-01'));setAmount('');setTransactionDirty(false);setNotice('Transaction saved. Your remaining allowances are updated.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function openTransaction(t:Saved<Transaction>){if(transactionDirty){setError('Save or cancel the current transaction first.');return;}setTransaction(structuredClone(t));setAmount((t.data.amountCents/100).toFixed(2));setTransactionDirty(true);setError('');}
 const summary=plan?budgetSummary(plan.data,transactions,month):null;
 return <section className="module-workspace"><div className="section-heading"><div><div className="eyebrow">MONEY</div><h2>Give your money a direction.</h2><p className="muted">{profile.moduleGoals.money||'Choose a money goal in My setup to guide future reviews.'}</p></div><label className="compact-field">Month<input aria-label="Budget month" type="month" value={month} disabled={busy||planDirty||transactionDirty} onChange={e=>{if(e.target.value)setMonth(e.target.value);}}/></label></div>
 {error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}{!ready?<Button disabled={busy} onClick={load}>{busy?'Opening budget…':'Retry budget'}</Button>:plan&&summary&&transaction&&<fieldset disabled={busy}>
 <div className="metric-grid"><div><small>Income recorded</small><strong>{money(summary.income)}</strong></div><div><small>Expenses recorded</small><strong>{money(summary.expenses)}</strong></div><div><small>Saved / invested</small><strong>{money(summary.saving+summary.investing)}</strong></div><div><small>Recorded cash flow</small><strong>{money(summary.cashFlow)}</strong><small>Not a bank balance</small></div></div>
 <div className="module-columns"><div className="module-card"><h3>{transaction.version?'Edit transaction':'Quick transaction'}</h3><p className="muted">{transaction.data.recurringId?'Scheduled item selected. Confirm the actual amount and date.':'Log what actually moved. Savings and investments are transfers.'}</p><div className="form-grid"><label className="compact-field">Type<Choice label="Transaction type" value={transaction.data.kind} onChange={kind=>editTransaction({...transaction.data,kind:kind as Transaction['kind'],categoryId:''})} options={transaction.data.recurringId?kinds.filter(k=>k.value===transaction.data.kind):kinds}/></label><label className="compact-field">Amount (USD)<input inputMode="decimal" placeholder="0.00" value={amount} onChange={e=>{setAmount(e.target.value);setTransactionDirty(true);}}/></label><label className="compact-field">Date<input type="date" min={month+'-01'} max={month===today.slice(0,7)?today:dueDate(month,31)} value={transaction.data.date} onChange={e=>editTransaction({...transaction.data,date:e.target.value})}/></label>{transaction.data.kind==='expense'&&<label className="compact-field">Category<Choice label="Expense category" value={transaction.data.categoryId} options={plan.data.categories.filter(c=>!transaction.data.recurringId||c.id===transaction.data.categoryId).map(c=>({value:c.id,label:c.name}))} onChange={categoryId=>editTransaction({...transaction.data,categoryId})}/></label>}</div><label className="compact-field">Description<input maxLength={300} placeholder="e.g. Lunch" value={transaction.data.note} onChange={e=>editTransaction({...transaction.data,note:e.target.value})}/></label>{transaction.version>0&&<label className="inline-check"><input type="checkbox" checked={transaction.data.voided} onChange={e=>editTransaction({...transaction.data,voided:e.target.checked})}/>Void this transaction (keep its record)</label>}<div className="action-row"><Button disabled={!amount||!plan.version||planDirty} onClick={saveTransaction}>Save transaction</Button><Button variant="ghost" onClick={()=>{setTransaction(blankTransaction(month===today.slice(0,7)?today:month+'-01'));setAmount('');setTransactionDirty(false);}}>Cancel</Button></div>{(!plan.version||planDirty)&&<small>Save your monthly plan before logging transactions.</small>}</div>
 <div className="module-card"><h3>Category allowances</h3><p className="muted">Remaining = allowance minus recorded expenses.</p>{summary.categories.map(c=><div className="allowance-row" key={c.id}><div><strong>{c.name}</strong><span className={c.remaining<0?'negative':''}>{money(c.remaining)} left</span></div><progress aria-label={`${c.name} allowance used`} value={Math.min(c.spent,c.limitCents)} max={c.limitCents||1}/><small>{money(c.spent)} of {money(c.limitCents)} used{c.scheduled>0?` · ${money(c.scheduled)} still scheduled; ${money(c.afterScheduled)} after those payments`:''}</small></div>)}</div></div>
 <Accordion type="single" collapsible className="module-card" defaultValue={!plan.version?'plan':undefined}><AccordionItem value="plan"><AccordionTrigger>Monthly plan, payments & goals</AccordionTrigger><AccordionContent><p className="muted">USD for this beta. This month’s plan is saved separately; a new month carries forward the latest earlier plan for review.</p><h3 className="subheading">Monthly category allowances</h3>{plan.data.categories.map(c=><div className="editable-row" key={c.id}><label className="compact-field">Category<input maxLength={100} value={c.name} onChange={e=>editPlan({...plan.data,categories:plan.data.categories.map(x=>x.id===c.id?{...x,name:e.target.value}:x)})}/></label><Amount label="Allowance (USD)" cents={c.limitCents} onChange={limitCents=>editPlan({...plan.data,categories:plan.data.categories.map(x=>x.id===c.id?{...x,limitCents}:x)})}/></div>)}<Button variant="outline" disabled={plan.data.categories.length>=30} onClick={()=>editPlan({...plan.data,categories:[...plan.data.categories,{id:crypto.randomUUID(),name:'New category',limitCents:0}]})}>Add category</Button>
 <h3 className="subheading">Monthly payments & recurring income</h3><p className="muted">Days 29–31 fall on the last day in shorter months. Log a scheduled item once it happens; no money is moved by LifeApp.</p>{plan.data.recurring.map(r=><div className="recurring-editor" key={r.id}><label className="compact-field">Name<input maxLength={100} value={r.title} onChange={e=>editPlan({...plan.data,recurring:plan.data.recurring.map(x=>x.id===r.id?{...x,title:e.target.value}:x)})}/></label><Choice label="Scheduled item type" value={r.kind} options={kinds.slice(0,2)} onChange={v=>editPlan({...plan.data,recurring:plan.data.recurring.map(x=>x.id===r.id?{...x,kind:v as 'expense'|'income',categoryId:v==='income'?'':plan.data.categories[0]?.id||''}:x)})}/><Amount label="Amount (USD)" cents={r.amountCents} onChange={amountCents=>editPlan({...plan.data,recurring:plan.data.recurring.map(x=>x.id===r.id?{...x,amountCents}:x)})}/><label className="compact-field">Day of month<input type="number" min={1} max={31} value={r.day} onChange={e=>editPlan({...plan.data,recurring:plan.data.recurring.map(x=>x.id===r.id?{...x,day:Number(e.target.value)}:x)})}/></label>{r.kind==='expense'&&<Choice label="Scheduled expense category" value={r.categoryId} options={plan.data.categories.map(c=>({value:c.id,label:c.name}))} onChange={categoryId=>editPlan({...plan.data,recurring:plan.data.recurring.map(x=>x.id===r.id?{...x,categoryId}:x)})}/>}<label className="inline-check"><input type="checkbox" checked={r.active} onChange={e=>editPlan({...plan.data,recurring:plan.data.recurring.map(x=>x.id===r.id?{...x,active:e.target.checked}:x)})}/>Scheduled this month</label></div>)}<Button variant="outline" disabled={plan.data.recurring.length>=60} onClick={()=>editPlan({...plan.data,recurring:[...plan.data.recurring,{id:crypto.randomUUID(),title:'New monthly item',kind:'expense',categoryId:plan.data.categories[0]?.id||'',amountCents:100,day:1,active:true}]})}>Add monthly item</Button>
 <h3 className="subheading">What are you working toward?</h3>{(['spending','saving','investing'] as const).map(key=><label className="compact-field" key={key}>{key[0].toUpperCase()+key.slice(1)} goal<textarea rows={2} maxLength={1000} placeholder={`Describe your ${key} goal, target and timeframe`} value={plan.data.goals[key]} onChange={e=>editPlan({...plan.data,goals:{...plan.data.goals,[key]:e.target.value}})}/></label>)}<div className="action-row"><Button onClick={savePlan}>Save monthly plan</Button><Button variant="ghost" disabled={transactionDirty} onClick={load}>Cancel plan changes</Button></div></AccordionContent></AccordionItem></Accordion>
 <div className="module-card"><h3>Scheduled this month</h3>{!summary.due.length&&<p className="muted">Add monthly payments or recurring income in your plan.</p>}{summary.due.map(r=><div className="ledger-row" key={r.id}><span><strong>{r.title}</strong><small>{r.date} · {r.kind==='income'?'Income':'Payment'} · {r.recorded?'Recorded':'Not recorded'}</small></span><strong>{money(r.amountCents)}</strong><Button variant="outline" disabled={r.recorded||!plan.version||planDirty||month>today.slice(0,7)} onClick={()=>{const existing=transactions.find(t=>t.id===r.id);openTransaction(existing?{...existing,data:{...existing.data,voided:false}}:{id:r.id,version:0,data:{date:r.date>today?today:r.date,kind:r.kind,amountCents:r.amountCents,categoryId:r.categoryId,categoryName:'',note:r.title,recurringId:plan.data.recurring.find(x=>'due:'+month+':'+x.id===r.id)!.id,voided:false}});}}>Log</Button></div>)}</div>
 <div className="module-card"><h3>Transactions · {month}</h3>{!transactions.length&&<p className="muted">No transactions recorded for this month.</p>}{[...transactions].sort((a,b)=>b.data.date.localeCompare(a.data.date)).map(t=><div className="ledger-row" key={t.id}><span><strong>{t.data.note||kinds.find(k=>k.value===t.data.kind)?.label}{t.data.voided?' · Voided':''}</strong><small>{t.data.date} · {t.data.categoryName||kinds.find(k=>k.value===t.data.kind)?.label}</small></span><strong>{money(t.data.amountCents)}</strong><Button variant="ghost" onClick={()=>openTransaction(t)}>Edit</Button></div>)}</div><p className="muted">Personalized AI guidance is next. These totals use your recorded transactions only.</p>
 </fieldset>}</section>;
}
