"use client";
import {DateInput} from './date-input';
import {formatDate} from '@/lib/life/date-display';
import NumericInput from './numeric-input';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {recurringSchema,parseMoney,type Budget,type Saved} from '@/lib/life/modules';
import type {BudgetItemChange} from '@/lib/life/budget-items';
import {Choice} from './shared';
import {CurrencyInput,useBudgetDirty,useItemSave,type DirtyReporter} from './budget-fields';
type Recurring=Budget['recurring'][number];
export const weekdays=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
export function recurringDescription(item:Recurring){const repeat= item.frequency==='monthly-weekday'?`${item.week[0].toUpperCase()+item.week.slice(1)} ${weekdays[item.weekday]} each month`:`Day ${item.day} each month`;return repeat+(item.startDate?' · from '+formatDate(item.startDate):'')+(item.endDate?' · until '+formatDate(item.endDate):'')+(item.installments?' · '+item.installments+' payments':'');}
export default function RecurringDialog({item,previous,plan,onSave,onClose,onDirty,draftMode=false}:{draftMode?:boolean;item:Recurring;previous:Recurring|null;plan:Saved<Budget>;onSave:(change:BudgetItemChange)=>Promise<Saved<Budget>>;onClose:()=>void;onDirty:DirtyReporter}){
 const [draft,setDraft]=useState(item),[amount,setAmount]=useState(item.amountCents?(item.amountCents/100).toFixed(2):'');
 const [endMode,setEndMode]=useState(item.installments?'count':item.endDate?'date':'never'),[loanAmounts,setLoanAmounts]=useState({original:item.debt?.originalBalanceCents?(item.debt.originalBalanceCents/100).toFixed(2):'',balance:item.debt?.originalBalanceCents?(item.debt.balanceCents/100).toFixed(2):'',other:item.debt?(item.debt.otherPaymentCents/100).toFixed(2):'0',rate:item.debt?.originalBalanceCents?String(item.debt.annualRatePercent):''});
 const initialLoan=JSON.stringify({original:item.debt?.originalBalanceCents?(item.debt.originalBalanceCents/100).toFixed(2):'',balance:item.debt?.originalBalanceCents?(item.debt.balanceCents/100).toFixed(2):'',other:item.debt?(item.debt.otherPaymentCents/100).toFixed(2):'0',rate:item.debt?.originalBalanceCents?String(item.debt.annualRatePercent):''});
 const operation=useItemSave(onSave),dirty=JSON.stringify(loanAmounts)!==initialLoan||JSON.stringify(draft)!==JSON.stringify(item)||amount!==(item.amountCents?(item.amountCents/100).toFixed(2):'');
 useBudgetDirty('recurring-dialog',dirty||operation.busy||!!operation.pending,onDirty);
 function edit(patch:Partial<Recurring>){setDraft({...draft,...patch});operation.setError('');}
 async function save(change?:BudgetItemChange){
  try{if(!change&&endMode==='date'&&!draft.endDate)throw Error('Choose the final eligible date.');const mutation=change||{kind:'recurring' as const,month:plan.id,previous,item:recurringSchema.parse({...draft,amountCents:parseMoney(amount),...(draft.debt?{debt:{...draft.debt,originalBalanceCents:parseMoney(loanAmounts.original),balanceCents:parseMoney(loanAmounts.balance),otherPaymentCents:parseMoney(loanAmounts.other),annualRatePercent:loanAmounts.rate.trim()?Number(loanAmounts.rate):NaN}}:{})}),...(!plan.version?{initial:plan.data}:{})};if(await operation.submit(mutation))onClose();}
  catch(e){operation.setError(e instanceof Error&&'issues' in e?((e as unknown as {issues:{message:string}[]}).issues[0]?.message||'Check the loan and schedule details.'):'Enter valid amounts. Loan details need a balance, an interest rate (0 for interest-free) and a payment.');}
 }
 return <Dialog open onOpenChange={open=>{if(!open&&!operation.busy&&!operation.pending)onClose();}}><DialogContent className="recurring-dialog" showCloseButton={!operation.busy&&!operation.pending} onInteractOutside={e=>e.preventDefault()}>
 <DialogHeader><DialogTitle>{previous?.deleted?'Restore recurring item':previous?'Edit recurring item':draft.debt?'Add loan':'Add recurring item'}</DialogTitle><DialogDescription>Set the amount and when it repeats. {draftMode?'Review these values before adding them to your budget.':previous?'Changes apply to this month and future months copied from it.':'It will be included in this month’s budget.'}</DialogDescription></DialogHeader>
 <div className="recurring-dialog-body"><fieldset disabled={operation.busy||!!operation.pending}><label className="compact-field">Name<input maxLength={100} value={draft.title} placeholder="e.g. Electric bill" onChange={e=>edit({title:e.target.value})}/></label>
 <div className="form-grid"><label className="compact-field">Type<Choice label="Recurring type" value={draft.kind} options={[{value:'expense',label:'Expense'},{value:'income',label:'Income'}]} onChange={kind=>edit({debt:kind==='income'?undefined:draft.debt,kind:kind as Recurring['kind'],categoryId:kind==='income'?'':plan.data.categories.find(c=>!c.archived)?.id||''})}/></label>
 <CurrencyInput label={draft.variable?'Estimated amount':'Amount'} value={amount} onChange={setAmount}/></div>
 <label className="inline-check"><input type="checkbox" checked={draft.variable} onChange={e=>edit({variable:e.target.checked})}/>The actual amount varies</label>{draft.variable&&<p className="field-hint">Use your best estimate. We’ll remind you to enter the actual amount when it’s due.</p>}
 <div className="form-grid"><label className="compact-field">Repeat by<Choice label="Recurring frequency" value={draft.frequency} options={[{value:'monthly-day',label:'Day of month'},{value:'monthly-weekday',label:'Weekday of month'}]} onChange={frequency=>edit({frequency:frequency as Recurring['frequency']})}/></label>
 {draft.frequency==='monthly-day'?<label className="compact-field">Day<NumericInput min={1} max={31} value={draft.day} onValueChange={day=>edit({day})}/></label>:<><label className="compact-field">Which week<Choice label="Recurring week" value={draft.week} options={['first','second','third','fourth','last'].map(value=>({value,label:value[0].toUpperCase()+value.slice(1)}))} onChange={week=>edit({week:week as Recurring['week']})}/></label><label className="compact-field">Weekday<Choice label="Recurring weekday" value={String(draft.weekday)} options={weekdays.map((label,i)=>({value:String(i),label}))} onChange={weekday=>edit({weekday:Number(weekday)})}/></label></>}
 {draft.kind==='expense'&&<label className="compact-field">Category<Choice label="Recurring category" value={draft.categoryId} options={plan.data.categories.filter(c=>!c.archived||c.id===draft.categoryId).map(c=>({value:c.id,label:c.name}))} onChange={categoryId=>edit({categoryId})}/></label>}</div>
 <div className="form-grid"><div className="compact-field"><DateInput label="Starts on" clearable value={draft.startDate||''} onValueChange={startDate=>edit({startDate:startDate||undefined})}/></div><label className="compact-field">Ends<Choice label="Schedule end" value={endMode} options={[{value:'never',label:'No end date'},{value:'date',label:'On a date'},{value:'count',label:'After installments'}]} onChange={value=>{setEndMode(value);edit({endDate:value==='date'?draft.endDate||plan.id+'-28':undefined,installments:value==='count'?draft.installments||6:undefined,startDate:value==='count'?draft.startDate||plan.id+'-01':draft.startDate});}}/></label>
 {endMode==='date'&&<div className="compact-field"><DateInput label="Last eligible date" required value={draft.endDate||''} onValueChange={endDate=>edit({endDate:endDate||undefined})}/></div>}{endMode==='count'&&<label className="compact-field">Monthly installments<NumericInput min={1} max={600} value={draft.installments??NaN} onValueChange={installments=>edit({installments})}/></label>}</div>
 {endMode==='count'&&<p className="field-hint">Counts scheduled payments from the first due date on or after the start. Missed payments do not extend the schedule.</p>}
 {draft.kind==='expense'&&<label className="inline-check"><input type="checkbox" checked={!!draft.debt} onChange={e=>edit({debt:e.target.checked?{originalBalanceCents:0,balanceCents:0,balanceDate:plan.id+'-01',annualRatePercent:0,interestMethod:'monthly',otherPaymentCents:0}:undefined})}/>Track as a loan or debt</label>}
 {draft.debt&&<div className="loan-fields"><div className="form-grid"><CurrencyInput label="Original principal" value={loanAmounts.original} onChange={original=>setLoanAmounts({...loanAmounts,original})}/><CurrencyInput label="Statement principal balance" value={loanAmounts.balance} onChange={balance=>setLoanAmounts({...loanAmounts,balance})}/><div className="compact-field"><DateInput label="Balance as of (end of day)" required value={draft.debt.balanceDate} onValueChange={balanceDate=>edit({debt:{...draft.debt!,balanceDate}})}/></div><label className="compact-field">Annual interest rate (%)<input inputMode="decimal" value={loanAmounts.rate} placeholder="0 for interest-free" onChange={e=>setLoanAmounts({...loanAmounts,rate:e.target.value})}/></label><label className="compact-field">Interest estimate<Choice label="Interest method" value={draft.debt.interestMethod} options={[{value:'monthly',label:'Monthly (e.g. mortgage)'},{value:'daily',label:'Daily simple (e.g. student loan)'}]} onChange={value=>edit({debt:{...draft.debt!,interestMethod:value as 'monthly'|'daily'}})}/></label><CurrencyInput label="Taxes, insurance & fees in payment" value={loanAmounts.other} onChange={other=>setLoanAmounts({...loanAmounts,other})}/></div><p className="field-hint">Enter the interest rate, not APR. Estimates hold that rate steady. Update it when a promotional rate ends. Keep your statement balance current; fees and lender adjustments can change payoff.</p></div>}
 <label className="inline-check"><input type="checkbox" checked={draft.active} onChange={e=>edit({active:e.target.checked})}/>Active this month</label></fieldset>
 {operation.error&&<p role="alert" className="error">{operation.error}</p>}</div>
 <DialogFooter className="item-dialog-actions">{previous&&!previous.deleted&&!draftMode&&<Button variant="ghost" className="delete-item" disabled={operation.busy||!!operation.pending} onClick={()=>void save({kind:'recurring',month:plan.id,previous,item:{...previous,deleted:true,active:false},...(!plan.version?{initial:plan.data}:{})})}>Delete item</Button>}<Button variant="ghost" disabled={operation.busy||!!operation.pending} onClick={onClose}>Cancel</Button><Button disabled={operation.busy} onClick={()=>void save(operation.pending||undefined)}>{operation.busy?'Saving…':operation.pending?'Retry save':previous?.deleted?'Restore item':draftMode?'Keep changes':'Save'}</Button></DialogFooter>
 </DialogContent></Dialog>;
}
