"use client";
import {useState} from 'react';
import {ArrowUp,ArrowDown,ChevronDown,Plus,Trash2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {categorySchema,parseMoney,money,type Budget,type Saved} from '@/lib/life/modules';
import type {BudgetItemChange} from '@/lib/life/budget-items';
import {CurrencyInput,useBudgetDirty,useItemSave,type DirtyReporter} from './budget-fields';

type Category=Budget['categories'][number];
export default function BudgetOrder({plan,onSave,onClose,onDirty}:{plan:Saved<Budget>;onSave:(change:BudgetItemChange)=>Promise<Saved<Budget>>;onClose:()=>void;onDirty:DirtyReporter}){
 const [base]=useState(plan),[order,setOrder]=useState(()=>plan.data.categories.map(c=>c.id)),[items,setItems]=useState(()=>structuredClone(plan.data.categories)),[amounts,setAmounts]=useState(()=>Object.fromEntries(plan.data.categories.map(c=>[c.id,(c.limitCents/100).toFixed(2)]))),[open,setOpen]=useState<string|null>(null),[removing,setRemoving]=useState<string|null>(null),[announcement,setAnnouncement]=useState('');
 const operation=useItemSave(onSave),previous=base.data.categories.map(c=>c.id),appended=[...previous,...items.filter(c=>!previous.includes(c.id)).map(c=>c.id)],orderDirty=order.some((id,i)=>id!==appended[i]),locked=operation.busy||!!operation.pending;
 const dirty=orderDirty||JSON.stringify(items)!==JSON.stringify(base.data.categories)||items.some(c=>{const original=base.data.categories.find(b=>b.id===c.id);return !original||amounts[c.id]!==(original.limitCents/100).toFixed(2);});
 const visible=order.filter(id=>!items.find(c=>c.id===id)!.archived);
 useBudgetDirty('category-order',dirty||locked,onDirty);
 function edit(id:string,patch:Partial<Category>){setItems(list=>list.map(c=>c.id===id?{...c,...patch}:c));operation.setError('');}
 function add(){if(locked||items.length>=30)return;const item={id:crypto.randomUUID(),name:'',limitCents:0,archived:false};setItems(list=>[...list,item]);setOrder(list=>[...list,item.id]);setAmounts(values=>({...values,[item.id]:'0.00'}));setOpen(item.id);setRemoving(null);operation.setError('');setAnnouncement('New category added to your draft. Enter its name and monthly allowance.');}
 function removeDraft(id:string){if(locked)return;setItems(list=>list.filter(c=>c.id!==id));setOrder(list=>list.filter(value=>value!==id));setAmounts(values=>{const next={...values};delete next[id];return next;});setOpen(null);setRemoving(null);operation.setError('');setAnnouncement('New category removed from your draft.');}
 function move(id:string,direction:number){const index=visible.indexOf(id),next=visible[index+direction];if(!next||locked)return;const changed=[...order],a=changed.indexOf(id),b=changed.indexOf(next);[changed[a],changed[b]]=[changed[b],changed[a]];setOrder(changed);operation.setError('');setAnnouncement(`${items.find(c=>c.id===id)!.name} moved to position ${index+direction+1} of ${visible.length}.`);}
 async function save(){try{
  const categories=items.map(item=>({previous:base.data.categories.find(c=>c.id===item.id)||null,item:categorySchema.parse({...item,limitCents:parseMoney(amounts[item.id]||'0')})})).filter(c=>JSON.stringify(c.item)!==JSON.stringify(c.previous));
  if(await operation.submit(operation.pending||{kind:'category-edit',month:base.id,categories,...(orderDirty?{ordering:{previous,order}}:{}),...(!base.version?{initial:base.data}:{})}))onClose();
 }catch{operation.setError('Give every category a name and an allowance of zero or more.');}}
 return <Dialog open onOpenChange={next=>{if(!next&&!locked)onClose();}}><DialogContent className="category-order-dialog" showCloseButton={!locked} onInteractOutside={e=>e.preventDefault()}>
  <DialogHeader><DialogTitle>Edit categories</DialogTitle><DialogDescription>Add, reorder, rename or change this month’s allowances. Save applies your changes together.</DialogDescription></DialogHeader>
  <Button className="add-category" variant="ghost" disabled={locked||items.length>=30} onClick={add}><Plus/>Category</Button>
  <ol className="category-order-list">{visible.map((id,index)=>{const category=items.find(c=>c.id===id)!,original=base.data.categories.find(c=>c.id===id),name=original?.name||'New category';return <li key={id} className="category-edit-item"><div className="category-edit-heading"><span className="category-position" aria-hidden="true">{index+1}</span><button className="category-order-name" aria-expanded={open===id} onClick={()=>{setOpen(open===id?null:id);setRemoving(null);}}><ChevronDown aria-hidden="true"/><span>{category.name||(original?'Unnamed category':'New category')}<small>{money(Number.isFinite(Number(amounts[id]))?Math.round(Number(amounts[id])*100):category.limitCents)} / month</small></span></button><Button variant="ghost" size="icon" aria-label={`Move ${category.name||'new category'} up`} disabled={locked||index===0} onClick={()=>move(id,-1)}><ArrowUp aria-hidden="true"/></Button><Button variant="ghost" size="icon" aria-label={`Move ${category.name||'new category'} down`} disabled={locked||index===visible.length-1} onClick={()=>move(id,1)}><ArrowDown aria-hidden="true"/></Button></div>
   <div className="category-edit-fields" hidden={open!==id}><fieldset disabled={locked}><label className="compact-field">Category name<input aria-label={`${name} name`} autoFocus={!original} maxLength={100} value={category.name} onChange={e=>edit(id,{name:e.target.value})}/></label><CurrencyInput label="Monthly allowance" ariaLabel={`${name} allowance`} value={amounts[id]} onChange={value=>setAmounts({...amounts,[id]:value})}/></fieldset>
   {!original?<Button className="delete-category" variant="ghost" disabled={locked} onClick={()=>removeDraft(id)}><Trash2/>Remove new category</Button>:removing===id?<div className="category-delete-confirm"><p>Delete {category.name} from your allowances? Existing transactions and recurring items keep their category.</p><div className="action-row"><Button variant="destructive" disabled={locked} onClick={()=>{edit(id,{archived:true});setRemoving(null);setOpen(null);}}>Delete category</Button><Button variant="ghost" disabled={locked} onClick={()=>setRemoving(null)}>Keep category</Button></div></div>:<Button className="delete-category" variant="ghost" disabled={locked} onClick={()=>setRemoving(id)}><Trash2/>Delete category</Button>}</div>
  </li>;})}</ol>
  {items.some(c=>c.archived)&&<details className="removed-categories"><summary>Removed categories</summary>{items.filter(c=>c.archived).map(c=><div key={c.id}><span>{c.name}</span><Button variant="ghost" disabled={locked} onClick={()=>edit(c.id,{archived:false})}>{base.data.categories.find(b=>b.id===c.id)?.archived?'Restore':'Undo delete'}</Button></div>)}</details>}
  <span className="sr-only" role="status">{announcement}</span>{operation.error&&<p role="alert" className="error">{operation.error}</p>}
  <DialogFooter><Button variant="ghost" disabled={locked} onClick={onClose}>Cancel</Button><Button disabled={operation.busy||(!dirty&&!operation.pending)} onClick={()=>void save()}>{operation.busy?'Saving…':operation.pending?'Retry save':'Save changes'}</Button></DialogFooter>
 </DialogContent></Dialog>;
}
