"use client";
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {routineSchema,type Exercise,type Routine,type Saved,type Workout} from '@/lib/life/modules';
import {resolveExerciseName} from '@/lib/life/exercise-names';
import {definiteWorkoutRejection,sameRoutinePlan} from '@/lib/life/workout-session';
import {request,saveRecord,useWorkoutCancel} from './shared';

const matching=(routine:Routine,exercise:Exercise)=>{const name=resolveExerciseName(exercise.name);return routine.exercises.find(e=>e.id===exercise.id&&resolveExerciseName(e.name)===name)||routine.exercises.find(e=>resolveExerciseName(e.name)===name);};
export default function ExerciseSetupNotes({routine,workout,disabled,onSaved,onDirty}:{routine:Saved<Routine>;workout:Workout;disabled:boolean;onSaved:(routine:Saved<Routine>)=>void;onDirty:(dirty:boolean)=>void}){
 const [draft,setDraft]=useState(routine),[edited,setEdited]=useState<string[]>([]),[busy,setBusy]=useState(false),[pending,setPending]=useState<Saved<Routine>|null>(null),[error,setError]=useState(''),[conflict,setConflict]=useState<Saved<Routine>|null>();
 const dirty=edited.length>0;
 if(!dirty&&!busy&&!pending&&routine.version>draft.version)setDraft(routine);
 useEffect(()=>{onDirty(dirty||busy||!!pending);return()=>onDirty(false);},[dirty,busy,pending,onDirty]);
 useWorkoutCancel(()=>{if(busy||pending)return;setDraft(routine);setEdited([]);setConflict(undefined);setError('');},busy||!!pending);
 function acknowledge(saved:Saved<Routine>){onSaved(saved);setDraft(saved);setPending(null);setEdited([]);setConflict(undefined);setError('');}
 async function compare(record=pending||draft){try{const result=await request('?kind=routine'),saved:Saved<Routine>|undefined=result.records.find((r:Saved<Routine>)=>r.id===routine.id);if(!saved||!routineSchema.safeParse(saved.data).success){setConflict(null);return;}if(sameRoutinePlan(saved.data,record.data)&&saved.version>=record.version){acknowledge(saved);return;}if(saved.version>record.version){setPending(null);setConflict(saved);setError('');}else setConflict(null);}catch{setConflict(null);}}
 async function save(){if(busy||disabled||conflict!==undefined)return;const record=pending||draft,retrying=!!pending;setBusy(true);setPending(record);setError('');try{acknowledge(await saveRecord('routine',record));}catch(e){const status=(e as {status?:number}).status;setError((e as Error).message);if(status===409)await compare(record);else if(definiteWorkoutRejection(status,retrying,record.version))setPending(null);}finally{setBusy(false);}}
 const localChanges=draft.data.exercises.filter(e=>edited.includes(e.id)),mergeable=!!conflict&&!conflict.data.archived&&localChanges.every(e=>matching(conflict.data,e));
 function keepLocal(){if(!conflict||!mergeable)return;const base=conflict;setDraft({...base,data:{...base.data,exercises:base.data.exercises.map(exercise=>{const local=localChanges.find(e=>matching(base.data,e)?.id===exercise.id);return local?{...exercise,setupNote:local.setupNote}:exercise;})}});setEdited(localChanges.flatMap(e=>{const saved=matching(base.data,e);return saved?[saved.id]:[];}));onSaved(base);setConflict(undefined);setError('');}
 return <section className="exercise-setup-notes"><h3>Exercise setup notes</h3><p className="muted">Saved with this program for future sessions. Record your seat height, machine settings or position.</p><fieldset disabled={disabled||busy||!!pending||conflict!==undefined}>{workout.exercises.map(exercise=>{const saved=matching(draft.data,exercise);return <label key={exercise.id}>{exercise.name}{saved?<textarea rows={2} maxLength={2000} value={saved.setupNote||''} onChange={event=>{setEdited(previous=>previous.includes(saved.id)?previous:[...previous,saved.id]);setDraft({...draft,data:{...draft.data,exercises:draft.data.exercises.map(e=>e.id===saved.id?{...e,setupNote:event.target.value}:e)}});}}/>:<><p className="exercise-setup-snapshot">{exercise.setupNote||'No setup note saved for this exercise.'}</p><p className="muted">Save this exercise in the program to keep a reusable setup note.</p></>}</label>;})}</fieldset>
 {error&&<p className="error" role="alert">{error}</p>}
 {conflict!==undefined&&<div className="exercise-note-conflict"><h4>Review saved and local notes</h4>{conflict?<>{localChanges.map(local=><div key={local.id}><strong>{local.name}</strong><p>Saved: {matching(conflict.data,local)?.setupNote||'No saved note'}</p><p>Local: {local.setupNote||'No local note'}</p></div>)}<p className="muted">Keeping your notes preserves the latest program targets. Save notes separately after reviewing.</p><Button variant="secondary" disabled={busy} onClick={()=>acknowledge(conflict)}>Discard changes and use saved notes</Button><Button disabled={busy||!mergeable} onClick={keepLocal}>Keep my setup notes</Button>{!mergeable&&<p className="muted">The saved program removed an edited exercise or was archived. Your local notes remain above for review.</p>}</>:<p className="muted">The saved program could not be read. Your local notes and any unconfirmed save are preserved.</p>}<Button variant="ghost" disabled={busy} onClick={async()=>{setBusy(true);await compare();setBusy(false);}}>Read saved notes again</Button></div>}
 {conflict===undefined&&(pending?<Button disabled={busy} onClick={()=>void save()}>{busy?'Saving notes…':'Retry setup notes save'}</Button>:dirty&&<Button disabled={busy||disabled} onClick={()=>void save()}>Save setup notes</Button>)}
 </section>;
}
