"use client";
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import { Checkbox } from '@/components/ui/checkbox';
import { Choice } from './shared';
import { type ReviewPreferences, type Cadence } from '@/lib/life/reviews';
export default function ReviewSettings({value,onChange}:{value:ReviewPreferences;onChange:(v:ReviewPreferences)=>void}){
 const labels:Record<Cadence,string>={daily:'Daily',weekly:'Weekly',monthly:'Monthly',annual:'Annual'};
 return <div className="review-settings"><h3>Your AI feedback</h3><p className="muted">Save how you want LifeApp to support you. Daily reviews can be requested from a completed check-in once the AI connection is activated. Automatic daily analysis requires the separate opt-in below. Report emails use the separate opt-in below. Weekly, monthly, annual and biography generation are not active yet.</p><label className="compact-field">What do you want from your analysis?<textarea rows={3} maxLength={1500} value={value.intent} placeholder="Be specific about the help you want, what to focus on, and what kind of feedback is useful to you." onChange={e=>onChange({...value,intent:e.target.value})}/></label>
 <Accordion type="multiple">{(['daily','weekly','monthly','annual'] as Cadence[]).map(c=><AccordionItem value={c} key={c}><AccordionTrigger>{labels[c]} feedback · {value[c].enabled?'Enabled when connected':'Off'}</AccordionTrigger><AccordionContent><label className="inline-check"><Checkbox checked={value[c].enabled} onCheckedChange={v=>onChange({...value,[c]:{...value[c],enabled:!!v}})}/>Enable {c} reviews</label><div className="form-grid"><label className="compact-field">Preferred local time<input type="time" value={value[c].time} onChange={e=>onChange({...value,[c]:{...value[c],time:e.target.value}})}/></label><label className="compact-field">Tone<Choice label={`${labels[c]} tone`} value={value[c].tone} options={['balanced','gentle','direct'].map(v=>({value:v,label:v[0].toUpperCase()+v.slice(1)}))} onChange={v=>onChange({...value,[c]:{...value[c],tone:v as ReviewPreferences['daily']['tone']}})}/></label><label className="compact-field">Depth<Choice label={`${labels[c]} depth`} value={value[c].detail} options={['brief','standard','detailed'].map(v=>({value:v,label:v[0].toUpperCase()+v.slice(1)}))} onChange={v=>onChange({...value,[c]:{...value[c],detail:v as ReviewPreferences['daily']['detail']}})}/></label>
 {c==='weekly'&&<label className="compact-field">Day<Choice label="Weekly review day" value={String(value.weekDay)} options={['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((label,i)=>({value:String(i),label}))} onChange={v=>onChange({...value,weekDay:Number(v)})}/></label>}
 {c==='monthly'&&<label className="compact-field">Day of month<input type="number" min={1} max={31} value={value.monthDay} onChange={e=>onChange({...value,monthDay:Number(e.target.value)})}/></label>}
 {c==='annual'&&<><label className="compact-field">Month<input type="number" min={1} max={12} value={value.annualMonth} onChange={e=>onChange({...value,annualMonth:Number(e.target.value)})}/></label><label className="compact-field">Day<input type="number" min={1} max={31} value={value.annualDay} onChange={e=>onChange({...value,annualDay:Number(e.target.value)})}/></label></>}</div><label className="compact-field">What should the {c} review emphasize?<textarea maxLength={1500} rows={3} value={value[c].focus} placeholder={c==='daily'?'What happened, what helped, and one useful improvement':'Trends, meaningful activities, progress toward goals, and relevant earlier reviews'} onChange={e=>onChange({...value,[c]:{...value[c],focus:e.target.value}})}/></label><small>{c==='daily'?'Reviews cover the prior day only after its check-in is complete.':`Reviews cover the prior ${c==='weekly'?'calendar week':c==='monthly'?'calendar month':'calendar year'} and use source entries alongside earlier completed reviews.`} Days beyond a month’s length use its final day.</small></AccordionContent></AccordionItem>)}</Accordion>
 <label className="inline-check"><Checkbox checked={value.remindersEnabled} onCheckedChange={v=>onChange({...value,remindersEnabled:!!v})}/>Remind me when a check-in is missing or unfinished</label><p className="completion-help">Full-report email delivery has its own consent control below.</p>
 <label className="inline-check"><Checkbox checked={value.localEventsEnabled} onCheckedChange={v=>onChange({...value,localEventsEnabled:!!v})}/>Include optional local opportunities relevant to my goals</label>{value.localEventsEnabled&&<label className="compact-field">City or area for local events<input maxLength={200} value={value.eventArea} placeholder="A city or general area; no street address needed" onChange={e=>onChange({...value,eventArea:e.target.value})}/><small>Search results and recommendations will stay separate from your habit score.</small></label>}
 <label className="inline-check"><Checkbox checked={value.biographyEnabled} onCheckedChange={v=>onChange({...value,biographyEnabled:!!v})}/>Build an editable biography from my recorded experiences</label>{value.biographyEnabled&&<label className="compact-field">What should your biography capture?<textarea maxLength={1500} rows={3} value={value.biographyFocus} onChange={e=>onChange({...value,biographyFocus:e.target.value})}/><small>Future biography drafts should link to source dates and let you correct, exclude or remove inferred details.</small></label>}
 </div>;
}
