"use client";
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import { Checkbox } from '@/components/ui/checkbox';
import { Choice } from './shared';
import { type ReviewPreferences, type Cadence } from '@/lib/life/reviews';
export default function ReviewSettings({value,onChange}:{value:ReviewPreferences;onChange:(v:ReviewPreferences)=>void}){
 const labels:Record<Cadence,string>={daily:'Daily',weekly:'Weekly',monthly:'Monthly',annual:'Annual'};
 return <div className="review-settings"><h3>Your AI feedback</h3><p className="muted">Choose the focus, tone and schedule for your analyses. Automatic generation and full-report emails have separate controls below.</p><label className="compact-field">What do you want from your analysis?<textarea rows={3} maxLength={1500} value={value.intent} placeholder="Be specific about the help you want, what to focus on, and what kind of feedback is useful to you." onChange={e=>onChange({...value,intent:e.target.value})}/></label>
 <Accordion type="multiple">{(['daily','weekly','monthly','annual'] as Cadence[]).map(c=><AccordionItem value={c} key={c}><AccordionTrigger>{labels[c]} feedback · {value[c].enabled?'Enabled':'Off'}</AccordionTrigger><AccordionContent><label className="inline-check"><Checkbox checked={value[c].enabled} onCheckedChange={v=>onChange({...value,[c]:{...value[c],enabled:!!v}})}/>Include {c} analysis in my schedule</label><div className="form-grid"><label className="compact-field">Preferred local time<input type="time" value={value[c].time} onChange={e=>onChange({...value,[c]:{...value[c],time:e.target.value}})}/></label><label className="compact-field">Tone<Choice label={`${labels[c]} tone`} value={value[c].tone} options={['balanced','gentle','direct'].map(v=>({value:v,label:v[0].toUpperCase()+v.slice(1)}))} onChange={v=>onChange({...value,[c]:{...value[c],tone:v as ReviewPreferences['daily']['tone']}})}/></label><label className="compact-field">Depth<Choice label={`${labels[c]} depth`} value={value[c].detail} options={['brief','standard','detailed'].map(v=>({value:v,label:v[0].toUpperCase()+v.slice(1)}))} onChange={v=>onChange({...value,[c]:{...value[c],detail:v as ReviewPreferences['daily']['detail']}})}/></label>
 {c==='weekly'&&<label className="compact-field">Day<Choice label="Weekly analysis day" value={String(value.weekDay)} options={['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((label,i)=>({value:String(i),label}))} onChange={v=>onChange({...value,weekDay:Number(v)})}/></label>}
 {c==='monthly'&&<label className="compact-field">Day of month<input type="number" min={1} max={31} value={value.monthDay} onChange={e=>onChange({...value,monthDay:Number(e.target.value)})}/></label>}
 {c==='annual'&&<><label className="compact-field">Month<input type="number" min={1} max={12} value={value.annualMonth} onChange={e=>onChange({...value,annualMonth:Number(e.target.value)})}/></label><label className="compact-field">Day<input type="number" min={1} max={31} value={value.annualDay} onChange={e=>onChange({...value,annualDay:Number(e.target.value)})}/></label></>}</div><label className="compact-field">What should the {c} analysis emphasize?<textarea maxLength={1500} rows={3} value={value[c].focus} placeholder={c==='daily'?'What happened, what helped, and one useful improvement':'Trends, meaningful activities, progress toward goals, and relevant earlier analyses'} onChange={e=>onChange({...value,[c]:{...value[c],focus:e.target.value}})}/></label><small>{c==='daily'?'Analyses cover the prior day only after its check-in is complete.':`Analyses cover the prior ${c==='weekly'?'calendar week':c==='monthly'?'calendar month':'calendar year'} and use source entries alongside earlier completed analyses.`} Days beyond a month’s length use its final day.</small></AccordionContent></AccordionItem>)}</Accordion>
 <label className="inline-check"><Checkbox checked={value.remindersEnabled} onCheckedChange={v=>onChange({...value,remindersEnabled:!!v})}/>Remind me when a check-in is missing or unfinished</label><p className="completion-help">Full-report email delivery has its own consent control below.</p>
 </div>;
}
