"use client";
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {muscleIds,muscleNames,type MuscleId} from '@/lib/life/muscle-groups';
import {exerciseTargets} from '@/lib/life/muscle-volume';
import {exercisePresets,presetExercise,repTarget} from '@/lib/life/exercise-presets';
import {request} from './shared';
import {resolveExerciseName} from '@/lib/life/exercise-names';
import type {Exercise,Routine,Saved} from '@/lib/life/modules';
export default function RoutineEditor({routine,onChange,onSave,onCancel,busy,pending,error,initialExerciseId}:{initialExerciseId?:string;routine:Saved<Routine>;onChange:(r:Routine)=>void;onSave:()=>void;onCancel:()=>void;busy:boolean;pending:boolean;error:string}){
 const [exerciseId,setExerciseId]=useState(initialExerciseId||routine.data.exercises[0]?.id),[tab,setTab]=useState('targets');
 const [personal,setPersonal]=useState<Exercise[]>([]);useEffect(()=>{request('?personal-exercises').then(r=>setPersonal(r.exercises)).catch(()=>{});},[]);
 const data=routine.data,exercise=data.exercises.find(e=>e.id===exerciseId)||data.exercises[0],targets=exercise?exerciseTargets(exercise):null;
 function edit(patch:Partial<Exercise>){onChange({...data,exercises:data.exercises.map(e=>e.id===exercise.id?{...e,...patch}:e)});}
 function add(name:string){if(data.exercises.length>=30)return;const saved=personal.find(e=>resolveExerciseName(e.name)===resolveExerciseName(name));const e=saved?{...structuredClone(saved),id:crypto.randomUUID()}:presetExercise(name);onChange({...data,exercises:[...data.exercises,e]});setExerciseId(e.id);}
 function mapMuscle(id:MuscleId,role:string){const next={direct:(targets?.direct||[]).filter(m=>m!==id),indirect:(targets?.indirect||[]).filter(m=>m!==id)};if(role==='direct')next.direct.push(id);if(role==='indirect')next.indirect.push(id);edit({muscles:next});}
 return <><fieldset disabled={busy||pending}><div className="routine-basics"><label className="compact-field">Program name<input maxLength={100} value={data.name} onChange={e=>onChange({...data,name:e.target.value})}/></label><label className="compact-field">Sessions / week<select value={data.weeklySessions??''} onChange={e=>onChange({...data,weeklySessions:e.target.value===''?undefined:Number(e.target.value)})}><option value="">Not set</option>{Array.from({length:8},(_,n)=><option key={n} value={n}>{n===0?'0 · outside weekly plan':n}</option>)}</select></label></div>
 <div className="routine-editor-grid"><aside><div className="routine-exercise-list" aria-label="Program exercises">{data.exercises.map((e,i)=><button key={e.id} aria-pressed={exercise?.id===e.id} onClick={()=>setExerciseId(e.id)}><span>{i+1}. {e.name||'Untitled exercise'}</span><small>{e.sets} × {repTarget(e)}{!exerciseTargets(e)?' · map muscles':''}</small></button>)}</div><label className="compact-field">Add exercise<select value="" disabled={data.exercises.length>=30} onChange={e=>add(e.target.value)}><option value="">Choose from presets…</option><optgroup label="Personal presets">{personal.map(e=><option key={e.name}>{e.name}</option>)}</optgroup><optgroup label="Standard exercises">{exercisePresets.filter(e=>!personal.some(p=>resolveExerciseName(p.name)===resolveExerciseName(e.name))).map(e=><option key={e.name}>{e.name}</option>)}</optgroup></select></label><Button variant="ghost" disabled={data.exercises.length>=30} onClick={()=>add('Custom exercise')}>+ Custom exercise</Button></aside>
 {exercise?<div className="exercise-focus"><label className="compact-field">Exercise name<input maxLength={100} value={exercise.name} onChange={e=>edit({name:e.target.value,muscles:undefined})}/></label><div className="coverage-tabs" role="group" aria-label="Exercise settings"><button aria-pressed={tab==='targets'} onClick={()=>setTab('targets')}>Sets & targets</button><button aria-pressed={tab==='muscles'} onClick={()=>setTab('muscles')}>Muscle groups</button></div>
 {tab==='targets'?<div className="form-grid three">{[['Sets','sets',1,20],['Reps from','reps',1,100],['Reps to','repMax',1,100],['Starting load','load',0,2000],['Rest (seconds)','restSeconds',0,900]].map(([label,key,min,max])=><label className="compact-field" key={key}>{label}<input type="number" min={min} max={max} step={key==='load'?.25:1} value={exercise[key as 'sets']??exercise.reps} onChange={e=>edit({[key]:Number(e.target.value)})}/></label>)}<label className="compact-field">Load unit<select value={exercise.unit} onChange={e=>edit({unit:e.target.value as 'lb'|'kg'})}><option>lb</option><option>kg</option></select></label></div>:<><p className="coverage-caption">Primary work counts as direct. Assisting work counts as indirect. Adjust for how you perform the exercise.</p><div className="muscle-assignment">{muscleIds.map(id=><label key={id}>{muscleNames[id]}<select aria-label={muscleNames[id]+' role'} value={targets?.direct.includes(id)?'direct':targets?.indirect.includes(id)?'indirect':'none'} onChange={e=>mapMuscle(id,e.target.value)}><option value="none">Not counted</option><option value="direct">Direct · 1 set</option><option value="indirect">Indirect · ½ set</option></select></label>)}</div></>}
 <div className="action-row"><Button variant="ghost" disabled={data.exercises[0].id===exercise.id} onClick={()=>{const next=[...data.exercises],i=next.findIndex(e=>e.id===exercise.id);[next[i-1],next[i]]=[next[i],next[i-1]];onChange({...data,exercises:next});}}>Move earlier</Button><Button variant="ghost" onClick={()=>onChange({...data,exercises:data.exercises.filter(e=>e.id!==exercise.id)})}>Remove exercise</Button></div></div>:<p>Add an exercise to this program.</p>}</div>
 <label className="compact-field">Equipment & preferences<textarea rows={2} maxLength={2000} value={data.preferences} onChange={e=>onChange({...data,preferences:e.target.value})}/></label>{routine.version>0&&<label className="inline-check"><input type="checkbox" checked={data.archived} onChange={e=>onChange({...data,archived:e.target.checked})}/>Archive program, keep its workouts</label>}
 </fieldset><footer className="workout-panel-footer">{error&&<p className="error" role="alert">{error}</p>}{pending&&<p className="muted">Save unconfirmed. Retry the same changes.</p>}<div className="action-row"><Button disabled={busy||!data.exercises.length} onClick={onSave}>{busy?'Saving…':pending?'Retry program save':'Save program'}</Button><Button variant="ghost" disabled={busy||pending} onClick={onCancel}>Cancel changes</Button></div></footer></>;
}
