"use client";
import NumericInput from './numeric-input';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import type {StructuredWorkout} from '@/lib/life/modules';
import {muscleIds,muscleNames,type MuscleId} from '@/lib/life/muscle-groups';
import {exerciseTargets} from '@/lib/life/muscle-volume';
export default function StructuredWorkoutEditor({value,onChange}:{value:StructuredWorkout;onChange:(v:StructuredWorkout)=>void}){
 const [selected,setSelected]=useState(value.exercises[0]?.id),[musclesOpen,setMusclesOpen]=useState(false);
 const exercise=value.exercises.find(e=>e.id===selected)||value.exercises[0];
 function changeSets(sets:StructuredWorkout['sets']){onChange({...value,sets,exercises:value.exercises.map(e=>({...e,sets:Math.max(1,sets.filter(s=>s.exerciseId===e.id&&!s.warmup).length)}))});}
 if(!exercise)return <p>No structured exercises. Edit your description and organize it again.</p>;
 const sets=value.sets.filter(s=>s.exerciseId===exercise.id),targets=exerciseTargets(exercise)||{direct:[],indirect:[]};
 function edit(patch:Partial<typeof exercise>){onChange({...value,exercises:value.exercises.map(e=>e.id===exercise.id?{...e,...patch}:e)});}
 function role(id:MuscleId,role:string){const next={direct:targets.direct.filter(m=>m!==id),indirect:targets.indirect.filter(m=>m!==id)};if(role==='direct')next.direct.push(id);if(role==='indirect')next.indirect.push(id);edit({muscles:next});}
 return <div className="structured-workout"><label className="compact-field">Workout name<input value={value.name} maxLength={100} onChange={e=>onChange({...value,name:e.target.value})}/></label><label className="compact-field">Exercise<select value={exercise.id} onChange={e=>setSelected(e.target.value)}>{value.exercises.map(e=><option key={e.id} value={e.id}>{e.name} · {value.sets.filter(s=>s.exerciseId===e.id&&!s.warmup).length} working sets</option>)}</select></label><div className="form-grid"><label className="compact-field">Exercise name<input value={exercise.name} maxLength={100} onChange={e=>edit({name:e.target.value})}/></label><label className="compact-field">Load unit<select value={exercise.unit} onChange={e=>edit({unit:e.target.value as 'lb'|'kg'})}><option>lb</option><option>kg</option></select></label></div>
 <div className="written-set-head"><span>Reps</span><span>Load ({exercise.unit})</span><span>Warm-up</span></div>{sets.map((s,i)=><div className="written-set-row" key={exercise.id+':'+s.setNumber}><NumericInput aria-label={`Set ${i+1} reps`} min={0} max={100} value={s.reps} onValueChange={reps=>changeSets(value.sets.map(x=>x===s?{...x,reps}:x))}/><NumericInput aria-label={`Set ${i+1} load`} min={0} max={2000} step="any" value={s.load} onValueChange={load=>changeSets(value.sets.map(x=>x===s?{...x,load}:x))}/><input aria-label={`Set ${i+1} warm-up`} type="checkbox" checked={!!s.warmup} onChange={e=>changeSets(value.sets.map(x=>x===s?{...x,warmup:e.target.checked}:x))}/><Button variant="ghost" aria-label={`Remove set ${i+1}`} onClick={()=>changeSets(value.sets.filter(x=>x!==s))}>×</Button></div>)}
 <div className="action-row"><Button variant="secondary" disabled={sets.length>=40} onClick={()=>{let n=1;while(sets.some(s=>s.setNumber===n))n++;changeSets([...value.sets,{exerciseId:exercise.id,setNumber:n,reps:exercise.reps,load:0,warmup:false,completedAt:new Date().toISOString()}]);}}>Add completed set</Button><Button variant="ghost" onClick={()=>setMusclesOpen(v=>!v)} aria-expanded={musclesOpen}>Muscles & preset targets</Button><Button variant="ghost" onClick={()=>onChange({...value,exercises:value.exercises.filter(e=>e.id!==exercise.id),sets:value.sets.filter(s=>s.exerciseId!==exercise.id)})}>Remove exercise</Button></div>
 {musclesOpen&&<><p className="muted">Check these editable estimates. Saved exercises become personal presets.</p><div className="form-grid">{[['Reps from','reps'],['Reps to','repMax'],['Rest (seconds)','restSeconds']].map(([name,key])=><label className="compact-field" key={exercise.id+key}>{name}<NumericInput min={key==='restSeconds'?0:1} max={key==='restSeconds'?900:100} value={exercise[key as 'reps']??exercise.reps} onValueChange={next=>edit({[key]:next})}/></label>)}</div><div className="muscle-assignment">{muscleIds.map(id=><label key={id}>{muscleNames[id]}<select aria-label={muscleNames[id]+' role'} value={targets.direct.includes(id)?'direct':targets.indirect.includes(id)?'indirect':'none'} onChange={e=>role(id,e.target.value)}><option value="none">Not counted</option><option value="direct">Direct</option><option value="indirect">Indirect · ½</option></select></label>)}</div></>}
 </div>;
}
