"use client";
import TrainingAnalysis from './training-analysis';
import CardioLog from "./cardio";
import WorkoutNotes from './workout-notes';
import RoutineBuilder from './routine-builder';
import {presetExercise,repTarget,trainingSources} from '@/lib/life/exercise-presets';
import { useEffect, useRef, useState } from 'react';
import { Button } from '@/components/ui/button';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { ChevronDown, Pencil, Sparkles } from 'lucide-react';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import { todayIn, type Profile } from '@/lib/life/domain';
import { formatDate } from '@/lib/life/date-display';
import { nextSet, restRemaining, workoutTotals, type Routine, type Workout, type Exercise, type Saved } from '@/lib/life/modules';
import { request, saveRecord, useUnsaved } from './shared';
import WorkoutPanel from './workout-panel';
import RoutineEditor from './routine-editor';
import MuscleCoverage from './muscle-coverage';
import {volumeSources} from '@/lib/life/muscle-groups';
import type {TrainingSummary} from '@/lib/life/training-summary';
import './workouts.css';
const newExercise=presetExercise;
const newRoutine=():Saved<Routine>=>({id:crypto.randomUUID(),version:0,data:{name:'My workout',preferences:'',exercises:[newExercise()],archived:false}});
export default function Workouts({profile,onDirty,active:visible=true}:{active?:boolean;profile:Profile;onDirty:(v:boolean)=>void}){
 const [cardioHistory,setCardioHistory]=useState(false);
 const programMenuButton=useRef<HTMLButtonElement>(null),programBuildChoice=useRef<'manual'|'ai'|null>(null);
 const [cardioDirty,setCardioDirty]=useState(false),[notesDirty,setNotesDirty]=useState(false),[builderDirty,setBuilderDirty]=useState(false),[trainingBusy,setTrainingBusy]=useState(false);
 const [editorExerciseId,setEditorExerciseId]=useState<string|undefined>(),[mobileView,setMobileView]=useState('training'),[panel,setPanel]=useState<string|null>(null),[selectedId,setSelectedId]=useState(''),[incomplete,setIncomplete]=useState(false),[summary,setSummary]=useState<TrainingSummary|null>(null),[summaryError,setSummaryError]=useState(''),[warmup,setWarmup]=useState(false),[routinePending,setRoutinePending]=useState<Saved<Routine>|null>(null),[routineError,setRoutineError]=useState('');
 async function refreshSummary(){try{setSummary(await request('?training-summary'));setSummaryError('');}catch{setSummary(null);setSummaryError('Weekly totals could not be loaded.');}}
 function openEditor(r:Saved<Routine>,exercise?:string){if(routine){setPanel('editor');setRoutineError('Finish or cancel the current program draft first.');return;}const draft=structuredClone(r);if(exercise&&draft.data.exercises.length<30)draft.data.exercises.push(newExercise(exercise));setEditorExerciseId(exercise?draft.data.exercises.at(-1)?.id:undefined);setRoutine(draft);setRoutineDirty(!!exercise||draft.version===0);setRoutineError('');setPanel('editor');}

 const [routines,setRoutines]=useState<Saved<Routine>[]>([]),[sessions,setSessions]=useState<Saved<Workout>[]>([]),[routine,setRoutine]=useState<Saved<Routine>|null>(null),[routineDirty,setRoutineDirty]=useState(false),[setDirty,setSetDirty]=useState(false),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[reps,setReps]=useState(''),[load,setLoad]=useState(''),[clock,setClock]=useState(Date.now()),[vibration,setVibration]=useState(false),[supportsVibration,setSupportsVibration]=useState(false),[pending,setPending]=useState<Saved<Workout>|null>(null),[editingSet,setEditingSet]=useState<{exerciseId:string;setNumber:number}|null>(null);
 const alerted=useRef<string|null>(null),active=sessions.find(s=>!s.data.finishedAt&&!s.data.deleted),current=active?nextSet(active.data):null;
 useUnsaved(trainingBusy||notesDirty||builderDirty||cardioDirty||routineDirty||setDirty||(busy&&loaded)||!!pending||!!routinePending,onDirty);
 async function reload(){setBusy(true);setError('');try{const [r,w]=await Promise.all([request('?kind=routine'),request('?kind=workout')]);setRoutines(r.records);setIncomplete(r.hasMore);setSelectedId(id=>id||r.records.find((x:Saved<Routine>)=>!x.data.archived)?.id||'');setSessions(w.records);setLoaded(true);setNotice(w.hasMore?'Showing your current workout and 99 recent sessions.':'');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{reload();void refreshSummary();setSupportsVibration(typeof navigator.vibrate==='function');},[]);
 const currentKey=active?.id+':'+current?.exercise.id+':'+current?.setNumber;
 useEffect(()=>{setReps(String(current?.exercise.reps??0));setLoad(String(current?.exercise.load??0));setSetDirty(false);setEditingSet(null);setWarmup(false);},[currentKey]);
 useEffect(()=>{if(!active?.data.restUntil)return;const tick=()=>{const now=Date.now();setClock(now);const end=active.data.restUntil!;if(restRemaining(end,now)===0&&document.visibilityState==='visible'&&alerted.current!==end){alerted.current=end;if(vibration&&typeof navigator.vibrate==='function')navigator.vibrate([200,100,200]);}};tick();const timer=setInterval(tick,250);document.addEventListener('visibilitychange',tick);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',tick);};},[active?.data.restUntil,vibration]);
 function reviewDraft(draft:Saved<Routine>){openEditor(routines.find(r=>r.id===draft.id)||draft);}
 function cancelRoutine(){if(busy||routinePending)return;setRoutine(null);setRoutineDirty(false);setRoutineError('');setEditorExerciseId(undefined);setPanel(null);}
 function editRoutine(data:Routine){if(routine)setRoutine({...routine,data});setRoutineDirty(true);setNotice('');}
 async function saveRoutine(){const record=routinePending||routine;if(!record)return;setBusy(true);setRoutineError('');setRoutinePending(record);try{const saved=await saveRecord('routine',record);setRoutines(prev=>[saved,...prev.filter(r=>r.id!==saved.id)]);setSelectedId(saved.id);setRoutine(null);setRoutinePending(null);setRoutineDirty(false);setPanel(null);setNotice('Program saved. Existing workouts keep their original plan.');}catch(e){setRoutineError((e as Error).message);if((e as {status?:number}).status&&((e as {status:number}).status<500))setRoutinePending(null);}finally{setBusy(false);}}
 async function persistWorkout(record:Saved<Workout>){setPending(record);setBusy(true);setError('');try{const saved=await saveRecord('workout',record);setSessions(prev=>[saved,...prev.filter(s=>s.id!==saved.id)]);setPending(null);setWarmup(false);void refreshSummary();setSetDirty(false);setEditingSet(null);const next=nextSet(saved.data);setReps(String(next?.exercise.reps??0));setLoad(String(next?.exercise.load??0));setNotice(saved.data.finishedAt?'Workout saved to your history.':'Workout saved.');}catch(e){setError((e as Error).message);if((e as {status?:number}).status&&((e as {status:number}).status<500))setPending(null);}finally{setBusy(false);}}
 function start(r:Saved<Routine>){setMobileView('training');persistWorkout({id:crypto.randomUUID(),version:0,data:{date:todayIn(profile.timezone),routineId:r.id,name:r.data.name,exercises:structuredClone(r.data.exercises),sets:[],restUntil:null,finishedAt:null}});}
 function completeSet(){if(!active)return;const target=editingSet?{exercise:active.data.exercises.find(e=>e.id===editingSet.exerciseId)!,setNumber:editingSet.setNumber}:current;if(!target)return;
 if(!/^\d+$/.test(reps)||!/^\d+(\.\d{1,2})?$/.test(load)||Number(reps)>100||Number(load)>2000){setError('Enter 0–100 whole reps and a load from 0–2000.');return;}
 const completedAt=new Date().toISOString();const set={exerciseId:target.exercise.id,setNumber:target.setNumber,reps:Number(reps),load:Number(load),warmup,completedAt};
 const sets=[...active.data.sets.filter(s=>s.exerciseId!==set.exerciseId||s.setNumber!==set.setNumber),set];
 persistWorkout({...active,data:{...active.data,sets,restUntil:editingSet?active.data.restUntil:target.exercise.restSeconds?new Date(Date.now()+target.exercise.restSeconds*1000).toISOString():null}});
 }
 const remaining=restRemaining(active?.data.restUntil||null,clock),target=editingSet&&active?{exercise:active.data.exercises.find(e=>e.id===editingSet.exerciseId)!,setNumber:editingSet.setNumber}:current;
 const previous=active?sessions.find(s=>!s.data.deleted&&s.data.finishedAt&&s.data.routineId===active.data.routineId&&s.id!==active.id):undefined;
 return <section className="module-workspace training-workspace">
 <div className="training-week"><div><span className="eyebrow">THIS WEEK</span><strong>{summary?`${summary.current.sets} working sets · ${summary.current.sessions} session${summary.current.sessions===1?'':'s'}`:'Your training week'}</strong><small>{summary?`${formatDate(summary.current.from)} – ${formatDate(summary.today)} · Last full week: ${summary.previous.sets} sets`:summaryError||'Loading your logged training…'}</small></div></div>
 <TrainingAnalysis onBusy={setTrainingBusy}/><div className="training-toolbar"><div className="action-row"><Button variant="secondary" onClick={()=>setPanel('notes')}>{notesDirty?'Resume workout note':'Write workout'}</Button><Button variant="secondary" onClick={()=>{setCardioHistory(false);setPanel('cardio');}}>{cardioDirty?'Resume cardio':'Log cardio'}</Button><Button variant="ghost" onClick={()=>setPanel('history')}>History</Button></div><Button variant="ghost" disabled={busy||setDirty||!!pending} onClick={()=>{void reload();void refreshSummary();}}>Refresh</Button></div>
 {error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="analysis-note">{notice}</p>}
 <div className="coverage-tabs training-view-switch" role="group" aria-label="Workout workspace"><button aria-pressed={mobileView==='training'} onClick={()=>setMobileView('training')}>Programs & session</button><button aria-pressed={mobileView==='coverage'} onClick={()=>setMobileView('coverage')}>Muscle map</button></div>
 {!loaded?<Button disabled={busy} onClick={reload}>{busy?'Opening workouts…':'Retry workouts'}</Button>:<div className={`training-columns mobile-${mobileView}`}><div className="program-launcher">
 {pending&&<p className="notice">Workout save unconfirmed. <Button disabled={busy} onClick={()=>persistWorkout(pending)}>Retry workout save</Button></p>}
 <fieldset disabled={busy||!!pending}> {active&&<div className="gym-active"><div className="section-heading"><div><div className="eyebrow">CURRENT WORKOUT · {formatDate(active.data.date)}</div><h3>{active.data.name}</h3><small>{active.data.sets.filter(s=>!s.warmup).length} of {active.data.exercises.reduce((n,e)=>n+e.sets,0)} working sets logged · {active.data.sets.filter(s=>s.warmup).length} warm-ups</small></div><div className="rest-clock"><small>{active.data.restUntil?(remaining?'Rest':'Rest complete'):'Ready when you are'}</small><strong aria-label="Rest time remaining">{Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')}</strong>{active.data.restUntil&&<Button variant="secondary" onClick={()=>persistWorkout({...active,data:{...active.data,restUntil:null}})}>End rest</Button>}</div></div>
 {active.data.restUntil&&remaining===0&&<p className="notice" role="status">Rest complete. Ready for your next set.</p>}
 {target?<div className="current-set"><div><small>{editingSet?'CORRECT A LOGGED SET':`EXERCISE ${active.data.exercises.findIndex(e=>e.id===target.exercise.id)+1} OF ${active.data.exercises.length}`}</small><h2>{target.exercise.name}</h2><p>{editingSet?'Logged set '+target.setNumber:'Working set '+current?.workingSetNumber+' of '+target.exercise.sets} · target {repTarget(target.exercise)} reps · {target.exercise.restSeconds}s rest</p></div><div className="form-grid"><label className="compact-field">Reps completed<input type="number" inputMode="numeric" min={0} max={100} value={reps} onChange={e=>{setReps(e.target.value);setSetDirty(true);}}/></label><label className="compact-field">Load ({target.exercise.unit})<input inputMode="decimal" value={load} onChange={e=>{setLoad(e.target.value);setSetDirty(true);}}/><small>Use 0 for bodyweight.</small></label></div><label className="inline-check"><input type="checkbox" checked={warmup} onChange={e=>{setWarmup(e.target.checked);setSetDirty(true);}}/>Warm-up · keep the planned working set</label><div className="action-row"><Button onClick={completeSet}>{editingSet?'Save correction':'Save set & start rest'}</Button>{editingSet&&<Button variant="ghost" onClick={()=>{setEditingSet(null);setReps(String(current?.exercise.reps??0));setLoad(String(current?.exercise.load??0));setWarmup(false);setSetDirty(false);}}>Cancel correction</Button>}</div>{previous&&<p className="muted">Last time ({formatDate(previous.data.date)}): {previous.data.sets.filter(s=>s.exerciseId===target.exercise.id).map(s=>`${s.reps} × ${s.load} ${previous.data.exercises.find(e=>e.id===s.exerciseId)?.unit||""}`).join(' · ')||'No matching sets recorded.'}</p>}</div>:<p className="notice">All planned sets are logged. Finish when you’re ready.</p>}

<Button variant="ghost" disabled={setDirty} onClick={()=>persistWorkout({...active,data:{...active.data,deleted:true,restUntil:null}})}>Delete workout</Button>
<Button variant="ghost" onClick={()=>setPanel("sets")}>Plan & logged sets</Button>
 <Button variant="secondary" disabled={setDirty} onClick={()=>persistWorkout({...active,data:{...active.data,restUntil:null,finishedAt:new Date().toISOString()}})}>{current?'Finish workout with logged sets':'Finish workout'}</Button><small className="muted">Unlogged sets remain unrecorded and do not change habit scores.</small></div>}
</fieldset>
 <section className="training-card"><div className="section-heading"><h3>Your programs</h3><DropdownMenu modal={false}><DropdownMenuTrigger asChild><Button ref={programMenuButton} variant="ghost" disabled={busy} aria-label="New program">+ New<ChevronDown aria-hidden="true"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="life-menu" onCloseAutoFocus={event=>{const choice=programBuildChoice.current;programBuildChoice.current=null;if(!choice)return;event.preventDefault();programMenuButton.current?.focus();if(choice==='ai')setPanel('builder');else if(routine)setPanel('editor');else openEditor(newRoutine());}}><DropdownMenuItem onSelect={()=>{programBuildChoice.current='manual';}}><Pencil aria-hidden="true"/><span>Manual Build{routine&&<small className="muted"> · Resume edit</small>}</span></DropdownMenuItem><DropdownMenuItem onSelect={()=>{programBuildChoice.current='ai';}}><Sparkles aria-hidden="true"/><span>AI Build{builderDirty&&<small className="muted"> · Resume AI builder</small>}</span></DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>
 <div className="program-list">{!routines.some(r=>!r.data.archived)&&<p className="empty-inline">Create a training day or turn your routine description into a program.</p>}{routines.filter(r=>!r.data.archived).map(r=><article className={selectedId===r.id?'program-row selected':'program-row'} key={r.id}><button className="program-select" aria-pressed={selectedId===r.id} onClick={()=>setSelectedId(r.id)}><strong>{r.data.name}</strong><small>{r.data.exercises.length} exercises · {r.data.exercises.reduce((n,e)=>n+e.sets,0)} sets{r.data.weeklySessions===undefined?' · set frequency':` · ${r.data.weeklySessions}× / week`}</small></button><div className="program-actions"><Button variant="ghost" disabled={busy} onClick={()=>openEditor(r)} aria-label={'Edit '+r.data.name}>Edit</Button><Button disabled={!!active||busy||!!pending} onClick={()=>start(r)} aria-label={'Start '+r.data.name}>Start</Button></div></article>)}</div>
 {routines.some(r=>r.data.archived)&&<div className="action-row"><Button variant="ghost" onClick={()=>setPanel('archived')}>Archived</Button></div>}</section>
 </div><MuscleCoverage active={visible} viewKey={mobileView} routines={routines.filter(r=>!r.data.archived)} selectedId={routines.some(r=>r.id===selectedId&&!r.data.archived)?selectedId:routines.find(r=>!r.data.archived)?.id||''} onSelect={setSelectedId} summary={summary} incomplete={incomplete} onEdit={(id,exercise)=>{const r=routines.find(r=>r.id===id);if(r)openEditor(r,exercise);}} onGuide={()=>setPanel('guide')}/></div>}
 <WorkoutPanel open={panel==='editor'} title={routine?.version?'Edit program':'New program'} onClose={cancelRoutine} closeDisabled={busy||!!routinePending}>{routine&&<RoutineEditor key={routine.id} initialExerciseId={editorExerciseId} routine={routine} onChange={editRoutine} onSave={saveRoutine} onCancel={cancelRoutine} busy={busy} pending={!!routinePending} error={routineError}/>}</WorkoutPanel>
 <WorkoutPanel open={panel==='notes'} title="Write workout" onClose={()=>setPanel(null)}><WorkoutNotes profile={profile} onDirty={setNotesDirty} onSaved={()=>void refreshSummary()}/></WorkoutPanel>
 <WorkoutPanel open={panel==='cardio'} title="Cardio" onClose={()=>setPanel(null)}><CardioLog onCancel={()=>setPanel(null)} onSaved={()=>void refreshSummary()} profile={profile} onDirty={setCardioDirty} active={panel==='cardio'&&!cardioHistory}/></WorkoutPanel>
 <WorkoutPanel open={panel==='builder'} title="Build programs with AI" onClose={()=>setPanel(null)}><RoutineBuilder embedded onDirty={setBuilderDirty} onReview={reviewDraft} reviewDisabled={!!routine||busy||!!pending||setDirty}/></WorkoutPanel>
 <WorkoutPanel open={panel==='sets'} title="Plan & logged sets" onClose={()=>setPanel(null)}>{active&&<fieldset disabled={busy||!!pending}> {active.data.exercises.map(e=><div className="exercise-log" key={e.id}><strong>{e.name}</strong><small>{e.sets} sets × {repTarget(e)} target reps · {e.unit}</small>{active.data.sets.filter(s=>s.exerciseId===e.id).sort((a,b)=>a.setNumber-b.setNumber).map(s=><div className="ledger-row" key={s.setNumber}><span>{s.warmup?"Warm-up":"Set"} {s.setNumber}: {s.reps} reps × {s.load} {e.unit}</span><Button variant="ghost" disabled={setDirty} onClick={()=>{setEditingSet({exerciseId:e.id,setNumber:s.setNumber});setReps(String(s.reps));setLoad(String(s.load));setWarmup(!!s.warmup);setPanel(null);setSetDirty(true);}}>Correct</Button><Button variant="ghost" disabled={setDirty} onClick={()=>persistWorkout({...active,data:{...active.data,sets:active.data.sets.filter(x=>x!==s),restUntil:null}})}>Delete set</Button></div>)}</div>)}  <div className="timer-options"><label className="inline-check"><input type="checkbox" checked={vibration} disabled={!supportsVibration} onChange={e=>{setVibration(e.target.checked);if(e.target.checked)navigator.vibrate(100);}}/>Vibrate after rest {supportsVibration?'':'(unavailable in this browser)'}</label><small>Keep LifeApp open and your screen unlocked for alerts. Vibration depends on your browser and phone settings; the countdown restores after reload.</small></div></fieldset>}</WorkoutPanel>
 <WorkoutPanel open={panel==='history'} title="Workout history" onClose={()=>setPanel(null)}><div className="module-card"><div className="section-heading"><Button variant="ghost" onClick={()=>{setCardioHistory(true);setPanel('cardio');}}>Cardio history</Button><h3>Recent workout history</h3></div><p className="muted">Recorded sets and reps, with each exercise’s load volume. These records also inform your analyses.</p>{!sessions.some(s=>s.data.finishedAt)&&<p className="empty-inline">Finished workouts will appear here.</p>}<Accordion type="single" collapsible>{sessions.filter(s=>s.data.finishedAt&&!s.data.deleted).map(s=>{const totals=workoutTotals(s.data);return <AccordionItem value={s.id} key={s.id}><AccordionTrigger>{s.data.deleted?'Trash · ':''}{formatDate(s.data.date)} · {s.data.name} · {totals.sets} sets / {totals.reps} reps</AccordionTrigger><AccordionContent>{s.data.exercises.map(e=><div className="exercise-log" key={e.id}><strong>{e.name}</strong><p>{s.data.sets.filter(x=>x.exerciseId===e.id).sort((a,b)=>a.setNumber-b.setNumber).map(x=>`${x.reps} reps × ${x.load} ${e.unit}`).join(' · ')||'No sets recorded'}</p><small>Load volume: {totals.volume.find(v=>v.id===e.id)?.volume.toFixed(1)} {e.unit} × reps</small></div>)}<Button variant="ghost" disabled={busy||!!pending} onClick={()=>persistWorkout({...s,data:{...s.data,deleted:!s.data.deleted}})}>{s.data.deleted?'Restore':'Delete workout'}</Button></AccordionContent></AccordionItem>;})}</Accordion></div></WorkoutPanel>
 <WorkoutPanel open={panel==='archived'} title="Archived programs" onClose={()=>setPanel(null)}>{routines.filter(r=>r.data.archived).map(r=><div className="ledger-row" key={r.id}><span>{r.data.name}</span><Button onClick={()=>openEditor(r)}>Edit / restore</Button></div>)}</WorkoutPanel>
 <WorkoutPanel open={panel==='guide'} title="Understanding muscle coverage" onClose={()=>setPanel(null)}><div className="training-guidance"><p>The map estimates broad muscle groups. Direct work counts as one set; assisting work counts as half a set. Exercise technique, effort and individual anatomy change the actual stimulus. Select Muscle groups while editing any exercise to adjust its assignments.</p><p>ACSM’s 2026 guidance suggests around 10 weekly sets per muscle group for hypertrophy, with individualization and major muscle groups trained at least twice weekly. This is a reference, not a target everyone must meet or a reason to keep adding volume. The half-set estimate comes from separate research by Pelland and colleagues.</p><p>Program shows one session. Weekly plan multiplies saved sets by your chosen sessions per week; unset frequencies are excluded. This week counts only logged positive-rep working sets, including those in an ongoing workout. Warm-ups, unlogged sets, cardio and unstructured notes do not add to the map. Confirmed sets from written workouts count once. Older sets without a warm-up label are treated as working sets. Shoulders and core are grouped; coverage of one region does not mean every part received the same work.</p><p>Presets favor muscle growth with strength secondary: heavier lifts use lower rep ranges and longer rest. Adjust targets, starting loads and rest to maintain controlled, challenging sets and recover well.</p><ul>{[...volumeSources,...trainingSources.slice(1)].map(source=><li key={source.url}><a href={source.url} target="_blank" rel="noopener noreferrer">{source.title}</a></li>)}</ul></div></WorkoutPanel>
 </section>;
}
