"use client";
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {todayIn,type Profile} from '@/lib/life/domain';
import type {WorkoutNote,Saved} from '@/lib/life/modules';
import {request,saveRecord,useUnsaved} from './shared';
import {useItemSave} from './budget-fields';
import StructuredWorkoutEditor from './structured-workout-editor';
import type {WorkoutBuildResult} from '@/lib/life/workout-ai-schema';
import Dictation from './dictation';
const fresh=(date:string):Saved<WorkoutNote>=>({id:crypto.randomUUID(),version:0,data:{date,text:'',minutes:null,voided:false}});
export default function WorkoutNotes({profile,onDirty,onSaved}:{profile:Profile;onDirty:(v:boolean)=>void;onSaved?:()=>void}){
 const today=todayIn(profile.timezone),[records,setRecords]=useState<Saved<WorkoutNote>[]>([]),[form,setForm]=useState(()=>fresh(today)),[listening,setListening]=useState(false),[notice,setNotice]=useState(''),[loadError,setLoadError]=useState('');
 const [recovery,setRecovery]=useState<{sourceId:string;description:string;expiresAt:string}|null>(null);
 const [aiBusy,setAiBusy]=useState(false),[aiError,setAiError]=useState(''),[aiNotes,setAiNotes]=useState(''),[aiPending,setAiPending]=useState<{requestId:string;text:string;consent:true;recoveryOf?:string}|null>(null);
 const [drafts,setDrafts]=useState<{id:string;description:string;deleted?:boolean;status:string;result:WorkoutBuildResult|null}[]>([]);
 const [showTrash,setShowTrash]=useState(false);
 const operation=useItemSave((record:Saved<WorkoutNote>)=>saveRecord('workout-note',record)),locked=listening||operation.busy||!!operation.pending||aiBusy||!!aiPending;
 useUnsaved(!!form.data.text||form.data.minutes!==null||form.data.date!==today||form.version>0||locked,onDirty);
 async function load(){try{const result=await request('?kind=workout-note');setRecords(result.records);const builds=await request('?workout-builds');setDrafts(builds.builds);setRecovery(builds.recovery||null);setLoadError('');}catch{setLoadError('Workout notes could not be loaded.');}}
 useEffect(()=>{void load();},[]);
 function edit(patch:Partial<WorkoutNote>){setForm({...form,data:{...form.data,...patch}});setNotice('');operation.setError('');}
 async function save(record=form){const saved=await operation.submit(operation.pending||record);if(saved){setRecords(previous=>[saved,...previous.filter(n=>n.id!==saved.id)]);setForm(fresh(today));setAiNotes('');onSaved?.();setNotice(saved.data.deleted?'Workout moved to Trash.':saved.data.structured?'Workout saved. Confirmed sets now count toward muscle coverage; its exercises are available as personal presets.':'Workout note saved. It will inform your analyses.');}}
 async function organize(){
  const input=aiPending||{requestId:crypto.randomUUID(),text:form.data.text.trim(),consent:true as const,...(recovery?.description===form.data.text.trim()?{recoveryOf:recovery.sourceId}:{})};setAiPending(input);setAiBusy(true);setAiError('');
  try{const data=await request('',{action:'workout-build',build:input});const result=data.build.result as WorkoutBuildResult|null;void load();
   if(result){edit({structured:result.workout||undefined});setAiNotes(result.notes);setAiPending(null);}
   else if(data.build.status==='generating')setAiError('Still organizing. Check this draft again in a moment.');
   else {setAiError(data.build.status==='uncertain'?'This request could not be confirmed. It will not be sent again.':data.build.errorCode==='workout_output_truncated'?'AI returned an incomplete draft. Your original notes are unchanged; you can save them as written.':'AI returned a format the app could not validate. Your original notes are unchanged; you can save them as written.');setAiPending(null);}
  }catch(e){setAiError((e as Error).message);if((e as {status?:number}).status&&((e as {status:number}).status<500)){setAiPending(null);void load();}}finally{setAiBusy(false);}
 }
 async function removeDraft(d:typeof drafts[number]){setAiBusy(true);setAiError('');try{await request('',{action:'record-deletion',change:{kind:'build',id:'workout:'+d.id,deleted:!d.deleted}});await load();}catch(e){setAiError((e as Error).message);}finally{setAiBusy(false);}}
 return <section className="module-card workout-notes" aria-label="Workout notes"><h3>Write your workout</h3><p className="muted">Log it in your own words. Sets, weights, a walk, or simply how training felt.</p>
 <fieldset disabled={locked}><div className="form-grid"><label className="compact-field">Workout date<input type="date" max={today} value={form.data.date} onChange={e=>edit({date:e.target.value})}/></label><label className="compact-field">Minutes (optional)<input type="number" min={1} max={1440} value={form.data.minutes??''} onChange={e=>edit({minutes:e.target.value===''?null:Number(e.target.value)})}/></label></div><label className="compact-field">Workout notes<textarea rows={4} maxLength={5000} value={form.data.text} onChange={e=>edit({text:e.target.value})} placeholder="Push day: bench 3 × 8 at 135 lb, incline dumbbells, lateral raises. Felt strong; finished with a 20-minute walk."/></label>{form.version>0&&<label className="inline-check"><input type="checkbox" checked={form.data.voided} onChange={e=>edit({voided:e.target.checked})}/>Exclude this note from analysis and trends</label>}</fieldset>
 <Dictation value={form.data.text} onChange={text=>edit({text})} onListening={setListening} disabled={operation.busy||!!operation.pending||aiBusy||!!aiPending}/>
 {recovery&&<p className="analysis-note">One recovery retry is available for your previous workout.{recovery.description!==form.data.text.trim()&&<Button variant="ghost" disabled={locked||!!form.data.text||form.version>0} onClick={()=>{edit({text:recovery.description,structured:undefined});setAiNotes('');}}>Load previous workout</Button>}</p>}
 <p className="muted">Organize with AI sends this description and your Movement goal to Google Gemini. Check completed sets and muscle assignments before saving. Log each workout once.</p><div className="action-row"><Button variant="secondary" disabled={listening||operation.busy||!!operation.pending||aiBusy||form.data.text.trim().length<10} onClick={()=>void organize()}>{aiBusy?'Organizing…':aiPending?'Check this AI draft':recovery?.description===form.data.text.trim()?'Use recovery retry':'Organize with AI'}</Button></div>{aiError&&<p role="alert" className="error">{aiError}</p>}{aiNotes&&<p className="notice">{aiNotes}</p>}{form.data.structured&&<fieldset disabled={locked}><StructuredWorkoutEditor value={form.data.structured} onChange={structured=>edit({structured})}/><p className="muted">Saving confirms these sets were completed. Unspecified movements remain in the original note.</p></fieldset>}
 {operation.error&&<p className="error" role="alert">{operation.error}</p>}{notice&&<p role="status" className="analysis-note">{notice}</p>}
 <div className="action-row written-save"><Button disabled={listening||operation.busy||aiBusy||!!aiPending||!form.data.text.trim()} onClick={()=>void save()}>{operation.busy?'Saving…':operation.pending?'Retry save':form.data.structured?'Save workout':'Save workout note'}</Button><Button variant="ghost" disabled={locked} onClick={()=>{setForm(fresh(today));operation.setError('');}}>Cancel</Button></div>
 {loadError&&<p role="alert">{loadError}<Button variant="ghost" onClick={()=>void load()}>Retry notes</Button></p>}
 {drafts.length>0&&<details className="workout-note-history"><summary>AI drafts & Trash</summary>{drafts.map(d=><article key={d.id}><div className="section-heading"><span>{d.deleted?'Trash':d.result?.workout?.name||d.status}</span><div className="action-row">{!d.deleted&&d.result&&<Button variant="ghost" disabled={locked||!!form.data.text||form.version>0} onClick={()=>{setForm({...fresh(today),data:{...fresh(today).data,text:d.description,structured:d.result?.workout||undefined}});setAiNotes(d.result?.notes||'');}}>Use draft</Button>}<Button variant="ghost" disabled={locked} onClick={()=>void removeDraft(d)}>{d.deleted?'Restore':'Delete'}</Button></div></div></article>)}</details>}
 <details className="workout-note-history"><summary>Recent workout notes ({records.filter(r=>!r.data.deleted).length})</summary><Button variant="ghost" onClick={()=>setShowTrash(v=>!v)}>{showTrash?'Back to notes':'Trash'}</Button>{records.filter(n=>!!n.data.deleted===showTrash).map(n=><article key={n.id} className={n.data.voided?'note-excluded':''}><div className="section-heading"><strong>{n.data.date}{n.data.minutes!==null?` · ${n.data.minutes} min`:''}{n.data.deleted?' · Trash':n.data.voided?' · Excluded':''}</strong><Button variant="ghost" disabled={locked||n.data.deleted||!!form.data.text||form.version>0} onClick={()=>{setForm(structuredClone(n));setNotice('');}}>Edit note</Button><Button variant="ghost" disabled={locked||!!form.data.text||form.version>0} onClick={()=>void save({...n,data:{...n.data,deleted:!n.data.deleted}})}>{n.data.deleted?'Restore':'Delete'}</Button></div><p>{n.data.text}</p></article>)}</details></section>;
}
