"use client";
import { useEffect, useState } from "react";
import { Check, ArrowRight, Plus, Archive, LoaderCircle, BookOpen, SlidersHorizontal, CalendarDays, ShieldCheck } from "lucide-react";
import { useDraftSync } from "./life/use-draft-sync";
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel } from "@/components/ui/alert-dialog";
import AIReview from "./life/ai-review";
import ReviewSettings from "./life/review-settings";
import AccountSettings from "./life/account-settings";
import AutomaticReviewSettings from "./life/automatic-review-settings";
import { defaultReviewPreferences, completionIssues, previousDay, dailyReviewDecision } from "@/lib/life/reviews";
import BudgetPanel from "./life/budget";
import Workouts from "./life/workouts";
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { modules, standardHabits, score, todayIn, emptyEntry, type Entry, type Profile, type HabitStatus } from "@/lib/life/domain";

const freshProfile=():Profile=>({goal:"",reviewPreferences:defaultReviewPreferences(),moduleGoals:{},spiritualTradition:"",timezoneMode:"automatic",timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC",modules:["reflection"],habits:[],version:0});
const labels:Record<HabitStatus,string>={done:"Done",missed:"Missed",exempt:"Exempt",unrecorded:"Not recorded"};
async function api(body?:unknown){const r=await fetch("/api/life",{method:body?"POST":"GET",headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined,cache:"no-store"});const data=await r.json();if(!r.ok)throw new Error(data.error||"Unable to connect. Please try again.");return data;}
function niceDate(v:string){return new Date(v+"T12:00:00").toLocaleDateString(undefined,{weekday:"short",month:"short",day:"numeric"});}

export default function LifeApp({signOutHref="/signout-with-chatgpt?return_to=%2F"}:{signOutHref?:string}){
 const [profile,setProfile]=useState<Profile|null>(null),[config,setConfig]=useState<Profile|null>(null),[entries,setEntries]=useState<Entry[]>([]);
 const [deleted,setDeleted]=useState(false);
 const [initialConfig,setInitialConfig]=useState<Profile|null>(null);
 const [loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[tab,setTab]=useState("today"),[step,setStep]=useState(1),[habitName,setHabitName]=useState(""),[habitModule,setHabitModule]=useState<Profile["modules"][number]>("reflection");
 const sync=useDraftSync(entry=>setEntries(prev=>[entry,...prev.filter(e=>e.date!==entry.date)].sort((a,b)=>b.date.localeCompare(a.date))));
 const {draft,dirty}=sync;
 const [navigation,setNavigation]=useState<{run:()=>void|Promise<void>}|null>(null);
 const [aiBusy,setAiBusy]=useState(false);
 const [budgetDirty,setBudgetDirty]=useState(false),[gymDirty,setGymDirty]=useState(false);
 const setupDirty=!!config&&!!(profile||initialConfig)&&JSON.stringify(config)!==JSON.stringify(profile||initialConfig);
 const anyDirty=dirty||setupDirty||budgetDirty||gymDirty||aiBusy;
 async function load(){setError("");try{const data=await api();let p=data.profile as Profile|null;const detected=Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC";if(p&&p.timezoneMode==="automatic"&&p.timezone!==detected)p=(await api({action:"profile",profile:{...p,timezone:detected}})).profile;setProfile(p);const initial=p||freshProfile();setConfig(initial);setInitialConfig(initial);setEntries(data.entries);if(p)sync.open(data.entries.find((e:Entry)=>e.date===todayIn(p.timezone))||emptyEntry(p,todayIn(p.timezone)));setLoaded(true);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{load();},[]);
 useEffect(()=>{if(!anyDirty||deleted)return;const fn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue="";};window.addEventListener("beforeunload",fn);return()=>window.removeEventListener("beforeunload",fn);},[anyDirty,deleted]);
 function edit(next:Entry){sync.edit(next);setNotice("");}
 async function chooseDate(date:string){if(!profile||!date)return;if(dirty)await sync.flush();setBusy(true);setError("");try{let entry=entries.find(e=>e.date===date);if(!entry){const r=await fetch('/api/life?date='+encodeURIComponent(date),{cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.error);entry=data.entry;}sync.open(entry||emptyEntry(profile,date));setNotice("");setTab("today");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function saveProfile(){if(!config)return;setBusy(true);setError("");try{const data=await api({action:"profile",profile:config});setProfile(data.profile);setConfig(data.profile);if(!draft||draft.version===0)sync.open(emptyEntry(data.profile,draft?.date||todayIn(data.profile.timezone)));setNotice("Your setup is saved.");setTab("today");return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 async function saveEntry(){setBusy(true);setError("");try{await sync.finish();setNotice("Check-in complete. You can now request its AI review.");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function navigate(run:()=>void|Promise<void>){if(aiBusy){setError("Wait for the AI request to finish before leaving this section.");return;}if(anyDirty){setNavigation({run});return;}void run();}
 async function saveAndContinue(){if(!navigation)return;setError("");try{await sync.flush();if(setupDirty&&!(await saveProfile()))return;if(budgetDirty||gymDirty){setError("Save or cancel changes in the open Budget or Workouts form first.");setNavigation(null);return;}const run=navigation.run;setNavigation(null);await run();}catch(e){setError((e as Error).message);}}
 function discardAndContinue(){if(!navigation||sync.status==='saving'||budgetDirty||gymDirty)return;sync.discard();setConfig(profile||initialConfig);if(profile){if(draft)sync.open(entries.find(e=>e.date===draft.date)||emptyEntry(profile,draft.date));}const run=navigation.run;setNavigation(null);void run();}

 if(deleted)return <main className="onboarding"><h1>Your LifeApp account is deleted.</h1><p>Your saved personal records and sign-in sessions have been removed. Signing in again creates a new account.</p><a href="/sign-in">Return to sign-in</a></main>;
 const configFields=config&&<>
  <div className="field"><label htmlFor="goal">What would you like to make more room for?</label><input id="goal" maxLength={300} placeholder="e.g. Better routines and steady progress on my work" value={config.goal} onChange={e=>setConfig({...config,goal:e.target.value})}/></div>
  <div className="module-grid">{modules.map(m=><label className={`module-choice ${config.modules.includes(m.id)?"chosen":""}`} key={m.id}><span className="module-glyph">{m.glyph}</span><span><strong>{m.name}</strong><small>{m.hint}</small></span><Checkbox aria-label={m.name} checked={config.modules.includes(m.id)} onCheckedChange={checked=>{const next=checked?[...config.modules,m.id]:config.modules.filter(id=>id!==m.id);setConfig({...config,modules:next});if(!next.includes(habitModule)&&next.length)setHabitModule(next[0]);}}/></label>)}</div>
 <div className="section-goals"><h3>Give each section a purpose</h3><p className="muted">What would progress look like? Your goals will guide future reviews across your journal, habits and section logs.</p>{modules.filter(m=>config.modules.includes(m.id)).map(m=><label className="compact-field" key={m.id}>{m.name} goal<textarea maxLength={1000} rows={2} placeholder={`What would you like to work toward in ${m.name.toLowerCase()}?`} value={config.moduleGoals[m.id]||""} onChange={e=>setConfig({...config,moduleGoals:{...config.moduleGoals,[m.id]:e.target.value}})}/></label>)}{config.modules.includes("spiritual")&&<label className="compact-field">Tradition or approach (optional)<input maxLength={200} placeholder="Describe the tradition or approach you want respected" value={config.spiritualTradition} onChange={e=>setConfig({...config,spiritualTradition:e.target.value})}/></label>}</div>
 </>;
 function addHabit(title:string,module:Profile["modules"][number]){if(!config||!title.trim())return;setConfig({...config,habits:[...config.habits,{id:crypto.randomUUID(),title:title.trim(),module,archived:false}]});setHabitName("");}
 const habitFields=config&&<>
  <p className="muted">Choose a few habits you want to keep. Suggestions only count after you add them.</p>
  <div className="habit-picker"><Select value="" onValueChange={v=>{const [module,index]=v.split(":");const id=module as Profile["modules"][number];addHabit(standardHabits[id][Number(index)],id);}}><SelectTrigger aria-label="Add a standard habit" disabled={config.habits.length>=50}><SelectValue placeholder="Add a standard habit…"/></SelectTrigger><SelectContent>{modules.filter(m=>config.modules.includes(m.id)).flatMap(m=>standardHabits[m.id].map((title,i)=><SelectItem key={m.id+":"+i} value={m.id+":"+i} disabled={config.habits.some(h=>!h.archived&&h.title.toLowerCase()===title.toLowerCase())}>{m.name} · {title}</SelectItem>))}</SelectContent></Select><small>36 starting points across six sections. Edit any habit after adding it.</small></div>
  <div className="custom-habit"><input aria-label="Custom habit" maxLength={100} placeholder="Or write your own habit…" value={habitName} onChange={e=>setHabitName(e.target.value)}/><Select value={habitModule} onValueChange={v=>setHabitModule(v as typeof habitModule)}><SelectTrigger aria-label="Habit module"><SelectValue/></SelectTrigger><SelectContent>{modules.filter(m=>config.modules.includes(m.id)).map(m=><SelectItem value={m.id} key={m.id}>{m.name}</SelectItem>)}</SelectContent></Select><Button variant="secondary" disabled={!habitName.trim()||!config.modules.includes(habitModule)||config.habits.length>=50} onClick={()=>addHabit(habitName,habitModule)}>Add</Button></div>
  <div className="chosen-habits">{config.habits.filter(h=>!h.archived).map(h=><div key={h.id}><span><input aria-label={`Habit name: ${h.title}`} maxLength={100} value={h.title} onChange={e=>setConfig({...config,habits:config.habits.map(x=>x.id===h.id?{...x,title:e.target.value}:x)})}/><small>{modules.find(m=>m.id===h.module)?.name}{!config.modules.includes(h.module)?" · module paused":""}</small></span><Button variant="ghost" aria-label={`Archive ${h.title}`} onClick={()=>setConfig({...config,habits:config.habits.map(x=>x.id===h.id?{...x,archived:true}:x)})}><Archive/></Button></div>)}</div>

 </>;
 const summary=score(draft?.habits||[]);
 const yesterday=profile?previousDay(todayIn(profile.timezone)):null;
 const priorEntry=entries.find(e=>e.date===yesterday);
 const priorDecision=profile?dailyReviewDecision({enabled:profile.reviewPreferences.daily.enabled,entry:priorEntry}):null;
 const incompleteReasons=draft?completionIssues(draft):[];
 return <div className="app-shell"><header className="topbar"><a href="/" className="brand" aria-label="LifeApp home" onClick={e=>{if(anyDirty){e.preventDefault();navigate(()=>{window.location.assign("/");});}}}><span className="brand-mark">L</span>LifeApp</a><span className="beta-label">Private beta</span>{loaded&&signOutHref==="/sign-out"&&<AccountSettings disabled={busy||aiBusy||sync.status==="saving"||sync.status==="waiting"} onBusy={setBusy} onDeleted={()=>{sync.discard();setDeleted(true);}}/>}<a className="signout" href={signOutHref} target="_top" onClick={e=>{if(anyDirty){e.preventDefault();navigate(()=>{window.location.assign(signOutHref);});}}}>Sign out</a></header>
 <fieldset disabled={busy} className="contents">{!loaded?<main className="loading-state">{error?<><h1>We couldn’t open your journal.</h1><p role="alert">{error}</p><Button onClick={load}>Try again</Button></>:<><LoaderCircle className="spin"/><p>Opening your space…</p></>}</main>:!profile?<main className="onboarding"><div className="eyebrow">YOUR LIFE, YOUR CHOICES <span>{step} / 2</span></div><h1>{step===1?"What matters to you?":"Start small. Make it yours."}</h1><p className="intro">{step===1?"Choose the areas you’d like to check in on. You can change these anytime.":"Pick the habits you want to track, or begin with a simple journal."}</p>{error&&<p className="error" role="alert">{error}</p>}{step===1?configFields:habitFields}<div className="onboarding-footer">{step===2&&<Button variant="ghost" onClick={()=>setStep(1)}>Back</Button>}<span>About 2 minutes to set up</span><Button disabled={busy||!config?.modules.length} onClick={()=>step===1?setStep(2):saveProfile()}>{busy?<LoaderCircle className="spin"/>:null}{step===1?"Choose my habits":"Open my journal"}<ArrowRight/></Button></div><p className="privacy-note"><ShieldCheck/> Your journal is private. You choose when to request AI analysis.</p></main>:<main className="workspace">
 <div className="page-heading"><div><div className="eyebrow">A LITTLE ATTENTION, EVERY DAY</div><h1>Your daily space.</h1><p>{profile.goal||"A place for the habits and moments that matter to you."}</p></div></div>
 {yesterday&&priorDecision&&['missing','incomplete'].includes(priorDecision.state)&&<div className="completion-banner"><span><strong>Yesterday’s check-in {priorDecision.state==='missing'?'is missing':'is unfinished'}.</strong><small>Daily analysis waits for a complete entry. Missing information is never treated as failure.</small></span><Button variant="outline" disabled={busy} onClick={()=>navigate(()=>chooseDate(yesterday))}>Finish {yesterday}</Button></div>}
 <Tabs value={tab} onValueChange={v=>navigate(()=>{setError("");setTab(v);})}><TabsList className="main-tabs"><TabsTrigger value="today"><CalendarDays/>Check-in</TabsTrigger><TabsTrigger value="history"><BookOpen/>History</TabsTrigger>{profile.modules.includes("money")&&<TabsTrigger value="budget">Budget</TabsTrigger>}{profile.modules.includes("fitness")&&<TabsTrigger value="workouts">Workouts</TabsTrigger>}<TabsTrigger value="settings"><SlidersHorizontal/>My setup</TabsTrigger></TabsList>
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status"><Check/>{notice}</p>}
 <TabsContent value="today">{draft&&<div className="daily-layout"><section className="entry-panel"><div className="section-heading"><div><div className="eyebrow">{draft.date===todayIn(profile.timezone)?"TODAY":"YOUR JOURNAL"}</div><h2>{niceDate(draft.date)}</h2></div><input aria-label="Check-in date" type="date" max={todayIn(profile.timezone)} value={draft.date} disabled={busy} onChange={e=>{const date=e.target.value;if(date)navigate(()=>chooseDate(date));}}/></div>
 <div className="habits-heading"><h3>The habits you chose</h3><span>{draft.habits.length} habits</span></div>{!draft.habits.length?<p className="empty-inline">No habits selected. You can journal below or add habits in My setup.</p>:draft.habits.map(h=><div className="habit-row" key={h.id}><div><strong>{h.title}</strong><small>{modules.find(m=>m.id===h.module)?.name}</small></div><RadioGroup className="status-options" aria-label={h.title} value={h.status} onValueChange={status=>edit({...draft,habits:draft.habits.map(x=>x.id===h.id?{...x,status:status as HabitStatus}:x)})}>{(["done","missed","exempt","unrecorded"] as HabitStatus[]).map(s=><label key={s} className={`status-option ${h.status===s?"selected "+s:""}`}><RadioGroupItem value={s} aria-label={labels[s]}/><span>{labels[s]}</span></label>)}</RadioGroup></div>)}
 <div className="journal-field">{profile.moduleGoals.reflection&&<p className="goal-reminder">Your goal: {profile.moduleGoals.reflection}</p>}<label htmlFor="journal">A few words about your day</label><textarea id="journal" maxLength={6000} placeholder="What happened? What felt good? What got in the way?" rows={5} value={draft.journal} onChange={e=>edit({...draft,journal:e.target.value})}/></div>
 <div className="context-fields">{modules.filter(m=>m.id!=="reflection"&&(profile.modules.includes(m.id)||draft.context[m.id]!==undefined)).map(m=><div className="field" key={m.id}><label htmlFor={m.id}>{m.name}<span>Optional</span></label>{profile.moduleGoals[m.id]&&<p className="goal-reminder">Your goal: {profile.moduleGoals[m.id]}</p>}<textarea id={m.id} maxLength={2000} rows={2} placeholder={m.prompt} value={draft.context[m.id]||""} onChange={e=>edit({...draft,context:{...draft.context,[m.id]:e.target.value}})}/></div>)}</div>
 <div className="save-bar"><span>{sync.status==="saving"?"Syncing to cloud…":sync.status==="waiting"?"Waiting to sync…":sync.status==="error"?"Not synced":draft.version?"Saved to cloud":"Changes save automatically"}</span><div className="action-row">{sync.status==="error"&&<Button variant="outline" onClick={()=>sync.flush().catch(()=>{})}>Retry sync</Button>}<Button disabled={busy||sync.status==="saving"||incompleteReasons.length>0} onClick={saveEntry}>{busy?<LoaderCircle className="spin"/>:<Check/>}Finish check-in</Button></div></div>{sync.syncError&&<p className="error" role="alert">{sync.syncError} Your unsynced text is still in this tab.</p>}{incompleteReasons.length>0&&<p className="completion-help">Before analysis: {incompleteReasons.join(" ")}</p>}{draft.complete&&!dirty&&<p className="notice">Complete · ready for a review when the AI connection is active.</p>}</section>
 <aside className="review-panel"><div className="eyebrow">YOUR CHECK-IN AT A GLANCE</div><div className="score-number">{summary.percent===null?"—":summary.percent}<span>{summary.percent===null?"No score yet":"%"}</span></div><p className="score-caption">{summary.eligible?`${summary.done} of ${summary.eligible} recorded habits done`:"Record a habit to see your progress."}</p><div className="score-track" aria-hidden="true"><div style={{width:`${summary.percent||0}%`}}/></div><dl><div><dt>Done</dt><dd>{summary.done}</dd></div><div><dt>Missed</dt><dd>{summary.missed}</dd></div><div><dt>Exempt</dt><dd>{summary.exempt}</dd></div><div><dt>Not recorded</dt><dd>{summary.unrecorded}</dd></div></dl><p className="score-explainer">Only done and missed habits enter the score. Exempt and unrecorded habits stay separate.</p><div className="review-note"><h3>A check-in, not a verdict.</h3><p>Use this space to notice patterns. One day is only one part of the story.</p></div><p className="beta-note">This score uses your check-in only. AI reviews appear separately below.</p></aside></div>}{draft&&<AIReview key={draft.date} entry={draft} synced={!dirty} onBusy={setAiBusy}/>}</TabsContent>
 <TabsContent value="history"><section className="history-panel"><div className="section-heading"><div><div className="eyebrow">ONE DAY AT A TIME</div><h2>Your recent check-ins</h2></div><span>{entries.length} saved</span></div>{!entries.length?<div className="empty-history"><BookOpen/><h3>Your story starts with a check-in.</h3><p>Save your first day and it will appear here.</p><Button onClick={()=>setTab("today")}>Write today's check-in</Button></div>:entries.map(e=>{const s=score(e.habits);return <button key={e.date} className="history-row" disabled={busy} onClick={()=>navigate(()=>chooseDate(e.date))}><span className="history-date">{niceDate(e.date)}<small>{e.date.slice(0,4)}</small></span><span className="history-text">{e.journal||"Habit check-in"}<small>{e.complete?"Complete":"Draft"} · {s.done} done · {s.missed} missed · {s.exempt} exempt · {s.unrecorded} not recorded</small></span><span className="history-score">{s.percent===null?"—":s.percent+"%"}</span><ArrowRight/></button>})}</section></TabsContent>
 {profile.modules.includes("money")&&<TabsContent value="budget" forceMount className="data-[state=inactive]:hidden"><BudgetPanel profile={profile} onDirty={setBudgetDirty}/></TabsContent>}
 {profile.modules.includes("fitness")&&<TabsContent value="workouts" forceMount className="data-[state=inactive]:hidden"><Workouts profile={profile} onDirty={setGymDirty}/></TabsContent>}
 <TabsContent value="settings"><section className="settings-panel"><h2>Make room for what matters.</h2><p><a href="/api/life?export=1" download>Download my private data backup</a></p><p className="muted">Your saved check-ins keep their original habit names and choices.</p>{configFields}<h3>Your habits</h3>{habitFields}{config&&<ReviewSettings value={config.reviewPreferences} onChange={reviewPreferences=>setConfig({...config,reviewPreferences})}/>}<Accordion type="single" collapsible><AccordionItem value="advanced"><AccordionTrigger>Advanced settings</AccordionTrigger><AccordionContent><label className="inline-check"><Checkbox checked={config?.timezoneMode==="automatic"} onCheckedChange={v=>{if(config)setConfig({...config,timezoneMode:v?"automatic":"manual",timezone:v?Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC":config.timezone});}}/>Use my device timezone automatically</label><div className="field timezone"><label htmlFor="timezone">Timezone</label><input id="timezone" disabled={config?.timezoneMode==="automatic"} value={config?.timezone||"UTC"} onChange={e=>{if(config)setConfig({...config,timezone:e.target.value});}}/><small>Detected when you open LifeApp. A manual override uses an IANA name, such as America/New_York. Past entry dates stay the same.</small></div></AccordionContent></AccordionItem></Accordion><div className="save-bar"><span>Archived habits remain in past check-ins.</span><div className="action-row"><Button variant="ghost" onClick={()=>setConfig(profile)}>Cancel changes</Button><Button disabled={busy||!config?.modules.length} onClick={saveProfile}>{busy?<LoaderCircle className="spin"/>:null}Save setup</Button></div></div><AutomaticReviewSettings setupDirty={setupDirty}/></section></TabsContent></Tabs>
 <footer className="app-footer"><span>LifeApp · Small steps, seen clearly.</span><span>Private beta · No customer billing</span></footer>
 </main>}
 </fieldset><AlertDialog open={!!navigation} onOpenChange={open=>{if(!open)setNavigation(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Save before you leave?</AlertDialogTitle><AlertDialogDescription>{budgetDirty||gymDirty?"The open section has unsaved changes. Stay here to save or cancel its form.":"Your latest changes have not reached the cloud yet. Save them before continuing."}</AlertDialogDescription></AlertDialogHeader>{sync.syncError&&<p className="error" role="alert">{sync.syncError}</p>}<AlertDialogFooter><AlertDialogCancel>Stay here</AlertDialogCancel>{!budgetDirty&&!gymDirty&&<><Button variant="outline" disabled={sync.status==="saving"||busy} onClick={discardAndContinue}>Discard unsaved changes</Button><Button disabled={busy} onClick={saveAndContinue}>Save & continue</Button></>}</AlertDialogFooter></AlertDialogContent></AlertDialog></div>;
}
